### ISSUE TITLE
Handling Windows Python Alias Configuration in GPUStack Installation

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#100]
**Is your enhancement related to a problem? Please describe.**

https://github.com/user-attachments/assets/019dfa2d-68d2-4398-8a2b-21c03426ceb0">
https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/

Windows has a configuration for a Python alias. When this configuration is enabled, even if Python is not installed, there is still a Python command, run that python will open the Windows Store. If Python is not installed but this Python alias configuration is enabled, it may cause GPUStack to mistakenly believe that Python is already installed. 

GPUStack could support the case where it detects that the local Python is a Python alias, the GPUStack installation script should continue to install Python.

Workaround:
`Settings` -> `Apps` -> `Advanced app settings` -> `App execution aliases` -> disable: `App Installer, python.exe` and `App Install, python3.exe`

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(f530289)

**Test Result:**  pass
```
[INFO] Chocolatey already installed.
[INFO] Python command is just alias for open Windows Store, clean it up...
[INFO] Installing Python...
```
