### ISSUE TITLE
Make options for windows installation script consistent with the cli

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#106]
**Is your enhancement related to a problem? Please describe.**

The options are different from linux or the cli flags. Make them consistent.

For example, it's `--port` in cli and `-server-port` in windows installation script.

See https://docs.gpustack.ai/installation/installation-script/

**Additional context**

Keep compatibility with what we have right now. We can mark the inconsistent ones as deprecated and remove them in latter releases.

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(1d727f1)
- OS: Windows 11
- GPU: NVIDIA GeForce RTX 4090 24G 

**Test Result:**

The options `-s` , `-t` and `-d` are not supported.

**Comment by Finenyaco** [comment]
Verified in main (f8da674)
