### ISSUE TITLE
Support Install_Package_Source parameter to use Pypi mirror in China

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#107]
Currently the installation script supports install_package_source to specify the source to install GPUStack package. A sample path for gpustack package in pypi mirror is like this:

https://pypi.tuna.tsinghua.edu.cn/packages/14/7d/515fbb5d26d2b0b305e0c6673244af562426d85d909ec9700e5520eb68c0/gpustack-0.1.0-py3-none-manylinux2014_x86_64.whl

It's not easy to use because:
1. It contains random numbers in download path. User need to use pip with the specific mirror to know the exact url.
2. It's bound to specific OS arch and version.

We need to provide a easier way to switch the pypi source to mirrors in China.

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(f530289)

**Test Result:**
Add env variable `INSTALL_INDEX_URL`
- Windows: pass
- MacOS: pass
- Ubuntu: pass

Print logs like:
```
pipx >(install_package:245): Installing gpustack
installing gpustack...
pipx >(run_subprocess:175): running C:\Users\sophia\pipx\venvs\gpustack\Scripts\python.exe -m pip --no-input install --index-url https://pypi.tuna.tsinghua.edu.cn/simple gpustack
```
