### ISSUE TITLE
GPU not identified correctly in virtualization environment with GPU passthrough 

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#108]
Proxmox Virtual Environment  7.4, with Nvidia 4090 GPU PCI passthrough to a Ubuntu 22.10 VM. After GPUStack installation, the GPU was identified as Unknown Device 1111 (VGA compatible), index number 255 and 0 cores.

<img width="1557" alt="image" src="https://github.com/user-attachments/assets/5beed6aa-c7c1-4c17-b464-f93c3129f48e">

**Comment by pengjiang80** [comment]
This issue may be related
https://github.com/fastfetch-cli/fastfetch/issues/931

**Comment by CarterLi** [comment]
Please check if https://github.com/fastfetch-cli/fastfetch/commit/45659854d2202e56746d38048e0756bb69356d7f fixes this issue
