### ISSUE TITLE
Failed to load HuggingFace model although downloading percentage shows as100%

### ISSUE THREAD

**Issue by lruihan** [gpustack/gpustack#122]
**Describe the bug**

I want to load HuggingFace models, but it shows below error although downloading percentage shows as 100%.
There is no problem with Ollama.

**Steps to reproduce**

1. Go to Models page and check HuggingFace Models

**Result**
![hf_model_error](https://github.com/user-attachments/assets/bed1533f-4287-4ffe-8544-32ecf60690d8)

**Expected behavior**
The model should be running successfully.

**Environment**

- GPUStack version: 0.1.0
- OS: Ubuntu 22.04.4 LTS (Jammy Jellyfish)
- GPU: Nvidia

**Additional context**
![nvidia_smi](https://github.com/user-attachments/assets/01efb96f-beac-4bb7-ad26-6620b66c8380)

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Nov_18_09:45:30_PST_2021
Cuda compilation tools, release 11.5, V11.5.119
Build cuda_11.5.r11.5/compiler.30672275_0

**Comment by thxCode** [comment]
can you check whether to install the CUDA runtime? you can check with `ldd`.

FYI, https://github.com/gpustack/llama-box/actions/runs/10182061971/job/28168040793
<img width="699" alt="image" src="https://github.com/user-attachments/assets/dfa0bef4-b329-4062-91ad-79b95b046a6a">

**Comment by pengjiang80** [comment]
It seems your CUDA driver version is 12.2 and CUDA runtime version is 11.5. GPUStack has a built-in llama-box for CUDA 12 by default, which depends on libcudart.so.12. 

Could you upgrade your CUDA runtime to 12 and have a try?

**Comment by lruihan** [comment]
Sure, I am upgrading by using 
wget https://developer.download.nvidia.com/compute/cuda/12.6.0/local_installers/cuda_12.6.0_560.28.03_linux.run.
It seems slow to download, will get back to you after upgrade. Thank you!

**Comment by lruihan** [comment]
It works now after upgrading to cuda12.6, thank you!

**Comment by linyinli** [comment]
@lruihan You can check your current environment variable settings to ensure that `$PATH` points to the installation path of CUDA 12.6. (This may also include the `$CUDA_HOME` variable in some installation methods.) 

Typically, these settings are found in the `~/.bashrc` or `~/.zshrc` file, such as:
```
export PATH=$PATH:/usr/local/cuda-12.6/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-12.6/lib
```

**Comment by lruihan** [comment]
Got it, thanks for your answer!
