### ISSUE TITLE
GPUStack’s OpenAI-Compatible API not compatible with Open WebUI 

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#129]
**Describe the bug**
 GPUStack’s OpenAI-Compatible API cannot be accessed using the Open WebUI.

**Steps to reproduce**

1. Run Open WebUI container and set OpenAI API environments:
```
docker run -d -p 3000:8080 -e OPENAI_API_BASE_URL=http://192.168.x.x/v1-openai -e OPENAI_API_KEY=gpustack_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
```
2. Open `http://localhost:3000` to visit Open WebUI, log in and talking to the model.

**Result**
```
ERROR [apps.openai.main] 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://192.168.x.x/v1-openai/chat/completions')
Traceback (most recent call last):
  File "/app/backend/apps/openai/main.py", line 492, in generate_chat_completion
    response_data = await r.json()
                    ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1176, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: ', url=URL('http://192.168.x.x/v1-openai/chat/completions')
```

**Expected behavior**
 GPUStack’s OpenAI-Compatible API can be accessed using the Open WebUI.

**Environment**

- GPUStack version: v0.1.0
- OS: MacOS
- GPU: Apple Meta

**Additional context**
Access through the API provided by llama box is normal: http://192.168.x.x:40950/v1

**Comment by arnesund** [comment]
Also hit this issue, would be great to make a new release with that fix.

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(477c409)
- OS:  MacOS 14.2.1
- GPU: Apple M2, 24G

**Test Result:** pass

<img width="2546" alt="image" src="https://github.com/user-attachments/assets/73f324b3-9348-402b-b5b3-6db603c709fa">
