### ISSUE TITLE
Support detect the number of Moore Threads GPU core

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#134]
**Is your enhancement related to a problem? Please describe.**

Thank for @yeahdongcn support with the Moore Threads GPU. This issue is created to document a known problem: the MTML library currently has no interface to query the number of cores.

<img width="1072" alt="Screenshot 2024-08-03 at 22 24 29" src="https://github.com/user-attachments/assets/e4d76b1d-6804-48bb-89c4-49dd7af3df3f">

**Comment by yeahdongcn** [comment]
No problem. I'll return to this once the interface is provided.

**Comment by yeahdongcn** [comment]
Should be fixed by: https://github.com/gpustack/fastfetch/pull/3

**Comment by yeahdongcn** [comment]
This could be closed as well.
