### ISSUE TITLE
Update the parameter names of the Add Worker command for Windows

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#148]
**Describe the bug**
Due to https://github.com/gpustack/gpustack/issues/106, We need to update the parameter names of the Add Worker command for Windows:
-ServerURL > --server-url
-Token > --token

**Comment by Finenyaco** [comment]
**Test Result:** pass

UI version: a04773d

<img width="591" alt="image" src="https://github.com/user-attachments/assets/a3fb6241-858b-4cec-91e8-cde111756a28">
