### ISSUE TITLE
ERROR: Invalid requirement: "'--pre'" error occurs when installing the pre-release version of GPUStack on Windows

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#153]
**Describe the bug**
```powershell
$env:INSTALL_PRE_RELEASE = 1
Invoke-Expression "& { $((Invoke-WebRequest -Uri "https://raw.githubusercontent.com/gpustack/gpustack/main/install.ps1" -UseBasicParsing).Content)}"
```
<img width="1361" alt="image" src="https://github.com/user-attachments/assets/af5c4ebe-a249-438e-ae58-71e1580cca79">

**Environment**

- GPUStack version: 0.1.1rc1
- OS: Windows
- GPU: NVIDIA RTX 4090

**Comment by Finenyaco** [comment]
**Test Result:** pass

Script version: main [d27e349](https://github.com/gpustack/gpustack/commit/d27e3494ae98b0b14963f33fb519376f7032ffd1)

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/dbf5165e-7ab4-4a66-83d5-dd75aefe7db7">
