### ISSUE TITLE
wrong gpustack version for docker image 0.1.1rc1

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#156]
**Describe the bug**

![image](https://github.com/user-attachments/assets/ddea9966-cd40-4642-8d58-5e74abbc2dfc)

**Steps to reproduce**

**Result**

**Expected behavior**

**Environment**

- GPUStack version:
- OS:
- GPU:

**Additional context**

**Comment by Finenyaco** [comment]
Verified in v0.1.1
