### ISSUE TITLE
When install with mac new environment, need to upgrade python to install gpustack 

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#163]
**Is your enhancement related to a problem? Please describe.**

1. When creating a new Mac user
2. Then try to install gpustack, will add upgrade Python advise
```
tester-admin@Seals-Mac-Studio ~ % python3 --version
Python 3.9.6

tester-admin@Seals-Mac-Studio ~ %  curl -sfL https://raw.githubusercontent.com/gpustack/gpustack/main/install.sh | INSTALL_PRE_RELEASE=1 sh -s -
[INFO]  running as non-root, will use sudo for installation.
[ERROR]  Python version is less than 3.10. Please upgrade Python to at least version 3.10.
```

**Describe the solution you'd like**
May be also support python 3.9, so the Mac builtin python could be used

**Describe alternatives you've considered**

**Additional context**

**Comment by gitlawr** [comment]
Closing in favor of https://github.com/gpustack/gpustack/issues/295
