### ISSUE TITLE
The installation of GPUStack failed due to the absence of the PATH environment variable

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#176]
**Describe the bug**

The installation of GPUStack failed due to the absence of the PATH environment variable.

**Steps to reproduce**

1. Create a new user and add them to the sudo list.
2. Install GPUStack by executing `curl -sfL https://get.gpustack.ai | sh -s -`.
3. Verify the operational status of the GPUStack service.

**Result**

1. The logs of installation script.
```
pipx >(_symlink_package_resource:132): Force is true. Removing /Users/tester/.local/bin/gpustack.
  installed package gpustack 0.1.1, installed using Python 3.12.2
  These apps are now globally available
    - gpustack
pipx >(warn_if_not_on_path:474): ⚠️  Note: '/Users/tester/.local/bin' is not on your PATH environment variable. These apps will not be globally accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in your shell's config file (e.g. ~/.bashrc).
done! ✨ 🌟 ✨
[INFO]  Setting up GPUStack as a service using launchd.
[INFO]  Install complete. Run "gpustack" from the command line. (You may need to open a new terminal or re-login for the PATH changes to take effect.)
```

2. After re-logging into the shell, the command for gpustack is still not found.
```
(base) tester@MyHostName ~ % gpustack version
zsh: command not found: gpustack
```

3. The GPUStack service has not started
```
(base) tester@MyHostName gpustack % ls
uninstall.sh
```
```
(base) tester@MyHostName ~ % cat /var/log/gpustack.log
cat: /var/log/gpustack.log: No such file or directory
```
**Expected behavior**

**Environment**

- GPUStack version: v0.1.0
- OS: MacOS 14.2.1
- GPU: Apple M2, 24G

**Additional context**

**Comment by gitlawr** [comment]
Seems no longer valid

**Comment by Finenyaco** [comment]
Cannot be reproduced in main.
