### ISSUE TITLE
Failed to run gemma2

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#180]
**Steps to reproduce**

1. Run gemma2 from ollama

**Result**

The model instance is in error state

**Expected behavior**

It should be running

**Environment**

- GPUStack version: 0.1.1
- OS: Windows

**Additional context**

model instance logs:
```
...
llama_new_context_with_model: graph splits = 2
[1724200366] warming up the model with an empty run
D:\a\llama-box\llama-box\llama.cpp\src\llama.cpp:14628: GGML_ASSERT(strcmp(embd->name, "result_embd_pooled") == 0 && "missing embeddings tensor") failed
```

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(0c2cae7)
- OS: Windows 11
- GPU: NVIDIA GeForce RTX 4090

**Test Result:** pass
