### ISSUE TITLE
Support recursive search when searching model files from Huggingface

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#185]
**Is your enhancement related to a problem? Please describe.**
Currently, the search results do not include model files located in subdirectories when searching from Hugging Face.

**Describe the solution you'd like**
 Adding support for recursive search would help users find models that are stored within nested directories.

**Comment by Finenyaco** [comment]
**UI Version:** 76444f2

**Test Result:** pass

![Image](https://github.com/user-attachments/assets/634efcd4-d28b-4a6b-aea1-10e4999abf32)
