### ISSUE TITLE
Open two GPUStack tabs and log in to one of them, the other tab keeps switching between the original page and the login page

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#195]
**Describe the bug**
Open two GPUStack tabs and log in to one of them, the other tab keeps switching between the original page and the login page.

**Steps to reproduce**
1. Open two GPUStack tabs;
2. Log out of GPUStack in one tab and refresh the browser page;
3. Log out of GPUStack in another tab and refresh the browser page;
4. Login in the first tab;
5. View the second tab.

**Result**

https://github.com/user-attachments/assets/c1a8827f-008a-4a18-9c34-0d15a5408a7e

<img width="1508" alt="image" src="https://github.com/user-attachments/assets/ab86ca32-56b8-48ea-b9ec-c60ecfc53950">

**Environment**

- GPUStack version: 0.1.2rc1
- OS: macOS 14.5
- GPU: Apple Metal

**Comment by Finenyaco** [comment]
**Environment:**
- GPUStack version: v0.1.2rc2
- UI version: 9a0aeb4

**Test result:** pass
