### ISSUE TITLE
Support Pinned Backend Version

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#197]
Currently, the inference server (llama-box) version is bound with GPUStack. To fix bugs, add new features, or support new models, we need to upgrade GPUStack to upgrade the inference server. The underlying inference engines (llama.cpp, vLLM or others) are frequently released. The core logic (cluster management, scheduling, and others) of GPUStack has a lower iteration speed. It would be better to decouple these two. Thus we can upgrade/release llama-box more frequently to support new models, fix bugs.

**Comment by Finenyaco** [comment]
Verified on main 3babc6f
