### ISSUE TITLE
Did i screw up installation?

### ISSUE THREAD

**Issue by RealMrCactus** [gpustack/gpustack#198]
```# gpustack chat llama3 "tell me a joke."
\`Request to server failed: (404, 'Unknown', '<html>\r\n<head><title>404 Not Found</title></
head>\r\n<body>\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>nginx/1.18.0 (Ubuntu)</center>\r\n</
body>\r\n</html>\r\n')```

**Comment by gitlawr** [comment]
There is no nginx running in GPUStack. It seems your request is being directed to something else. Could you check that in your environment?

**Comment by RealMrCactus** [comment]
> There is no nginx running in GPUStack. It seems your request is being directed to something else. Could you check that in your environment?

it is installed

**Comment by gitlawr** [comment]
If the default port is occupied you can customize GPUStack listening port. Example for installation by script:
```
curl -sfL https://get.gpustack.ai | sh -s - --port 8888
```
Details for using the script: https://docs.gpustack.ai/installation/installation-script/
Details for the cli args: https://docs.gpustack.ai/cli-reference/start/

**Comment by RealMrCactus** [comment]
> If the default port is occupied you can customize GPUStack listening port. Example for installation by script:
> 
> ```
> curl -sfL https://get.gpustack.ai | sh -s - --port 8888
> ```
> 
> Details for using the script: https://docs.gpustack.ai/installation/installation-script/ Details for the cli args: https://docs.gpustack.ai/cli-reference/start/

can i change the worker port?

**Comment by RealMrCactus** [comment]
nevermind i got it
