### ISSUE TITLE
Is there a way to pick specific ollama models?

### ISSUE THREAD

**Issue by RealMrCactus** [gpustack/gpustack#206]
Like is there a way for example i could pick specifically `llama3.1:8b-instruct-q8_0`?

**Comment by gitlawr** [comment]
<img width="1569" alt="image" src="https://github.com/user-attachments/assets/34807715-8aef-42cd-abfc-9a137bd3a5ef">
Just input that in the `Ollama Model` field.

**Comment by RealMrCactus** [comment]
got it
