### ISSUE TITLE
Remove uid field in playground requests

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#209]
**Describe the bug**

Requests sent in the playground UI contains a uid field which is invalid per https://platform.openai.com/docs/api-reference/chat/create

<img width="1367" alt="image" src="https://github.com/user-attachments/assets/4b1f1cba-e81d-4ab0-aea0-3290b598e31f">

**Environment**

- GPUStack version: 0.1.2

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(4d42dce)
- UI version: 825683d
- OS: macOS 14.2.1
- GPU: Apple M2, 24G

**Test Result:** pass

<img width="870" alt="image" src="https://github.com/user-attachments/assets/85a1ae27-67d0-4042-a012-1a5b83d5bd05">
