### ISSUE TITLE
Cant find cuda

### ISSUE THREAD

**Issue by RealMrCactus** [gpustack/gpustack#211]
The server has cuda 12.2 but the script says it cant find it.
![image](https://github.com/user-attachments/assets/16babb70-518c-43dc-a42d-8ac047368f49)
![image](https://github.com/user-attachments/assets/8cd0b4c5-6a8d-4fa4-98f0-3a372d75172b)

**Comment by pengjiang80** [comment]
The installation script will also check the existence of nvcc or libcudart as below:

# Function to check CUDA for NVIDIA GPUs
check_cuda() {
  if command -v nvidia-smi > /dev/null 2>&1; then
    if ! command -v nvcc > /dev/null 2>&1 && ! ($SUDO ldconfig -p | grep -q libcudart); then
      fatal "NVIDIA GPU detected but CUDA is not installed. Please install CUDA."
    fi
  fi
}

Could you also check the output of 'command -v nvcc' and 'sudo ldconfig -p | grep -q libcudart'?

**Comment by gitlawr** [comment]
nvidia-smi reports the driver version but the script fails to find the CUDA runtime library. Can you verify if the CUDA runtime works?([example](https://docs.cloudera.com/cdsw/1.10.5/gpu/topics/cdsw-test-the-cuda-engine.html))

**Comment by gitlawr** [comment]
There are cases where cuda is installed, but the script generates a false alarm.
To reproduce:
1. Run `grep -l "cuda" /etc/ld.so.conf.d/*`
2. Comment out the config file content by adding `#`.
3. Run `sudo ldconfig` to update cache.
4. Now install gpustack.

Current workaround: comment out `check_cuda` in the script(https://get.gpustack.ai/install.sh) then install.

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(c8e8485)
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4080

**Test Result:**
```
[WARN]  NVIDIA GPU detected but CUDA is not installed. Please install CUDA.
[INFO]  Installing GPUStack...
pipx >(setup:1083): pipx version is 1.6.0
pipx >(setup:1084): Default python interpreter is '/root/miniconda3/bin/python3.12'
pipx >(package_name_from_spec:378): Determined package name: gpustack
pipx >(package_name_from_spec:379): Package name determined in 0.0s
pipx >(create_venv:162): Creating virtual environment
creating virtual environment...
pipx >(run_subprocess:175): running /root/miniconda3/bin/python3.12 -m venv --without-pip /root/.local/share/pipx/venvs/gpustack
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /root/.local/share/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python --version
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: gpustack[vllm]
pipx >(install_package:245): Installing gpustack from spec 'gpustack[vllm]'
installing gpustack from spec 'gpustack[vllm]'...
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python -m pip --no-input install gpustack[vllm]
pipx >(run_subprocess:175): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:349): get_venv_metadata_for_package: 478ms
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: gpustack[vllm]
pipx >(_symlink_package_resource:132): Force is true. Removing /root/.local/bin/gpustack.
  installed package gpustack 0.2.1, installed using Python 3.12.4
  These apps are now globally available
    - gpustack
done! ✨ 🌟 ✨
```
