### ISSUE TITLE
Support Rerank models and API

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#214]
Rerank support is a very common requirement in RAG scenarios,  we should support Rerank models and API asap.

**Comment by pengjiang80** [comment]
Refer to https://github.com/ggerganov/llama.cpp/pull/9510. As llama.cpp already has initial support for reranking, we may support this with llama-box first.

**Comment by Finenyaco** [comment]
GPUStack version: main(72d9d5f)

When integrating with Didy, using the port of the GPUStack server results in an error, but integration is successful when using the port of the reranker model instance directly.

![image](https://github.com/user-attachments/assets/e9d00bad-1859-426c-a02e-c03bcbfac6ee)

**Comment by Finenyaco** [comment]
Verified on main de9a368
