### ISSUE TITLE
Support Nvidia GPUs with Compute Capability < 8.0

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#216]
**Is your enhancement related to a problem? Please describe.**

Now we support Nvidia GPUs with compute capability over 8.0. Extend the support matrix.

**Additional context**
https://developer.nvidia.com/cuda-gpus

We expect to extend from `8.0+` to `6.0+`

**Comment by Finenyaco** [comment]
Validated in the main version b7609b9.
