### ISSUE TITLE
Manual scheduling selects GPU Index 1 but runs on Index 0

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#259]
**Describe the bug**
When manually scheduling and selecting GPU Index 1 via the GPU selector, the model instance actually runs on GPU Index 0. 

**Environment**

- GPUStack version: 5cb4f3b
- OS: Ubuntu 22.04
- GPU: Nvidia T4 / Nvidia V100

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(fa073a7)
- UI version: b6d5b45d
- OS: macOS 14.6.1
- GPU: Apple M2, 24G

**Test Result:** pass
