### ISSUE TITLE
Model deployment fail with GLIBC version not found error

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#270]
**Steps to reproduce**

1. Run GPUStack on ubuntu20.04 
2. Deploy a model

**Result**

![image](https://github.com/user-attachments/assets/1c85c661-caa1-46a9-a306-841ed312efa8)

**Environment**

- GPUStack version: 0.1.2
- OS: ubuntu20.04

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main
- OS: Ubuntu 20.04
- GPU: NVIDIA T4

**Test Result:** pass
