### ISSUE TITLE
Failed to upgrade the GPUStack from v0.1.2

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#281]
**Describe the bug**

**Steps to reproduce**

1. Install GPUstack v0.1.2
2. Upgrade the GPUStack to the latest version.

**Result**

1. Failed to upgraded.
![image](https://github.com/user-attachments/assets/0dadf8f9-4232-41cb-ac2b-4e67a06d1478)

**Expected behavior**

**Environment**

- GPUStack version: main (1578ff0)
- OS: Ubuntu 22.04
- GPU: None

**Additional context**

**Comment by gitlawr** [comment]
Ref: https://alembic.sqlalchemy.org/en/latest/batch.html

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(084b188)
- OS: Ubuntu 22.04

**Test Result:** 

Upgrading from 0.1.1/0.1.2 to main: pass
