### ISSUE TITLE
Env path was not updated when installing GPUStack as root user

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#289]
**Describe the bug**

Env $PATH was not updated and users can't use gpustack command in shell. 

**Steps to reproduce**

1. Create a Ubuntu 22.04 VM (Tencent Cloud or others).
2. Sudo -s to switch to root user.
3. Run the installation script.
4. Logout and relogin, also run source ~/.bashrc
5. /home/root/.local/bin was not added to the env $PATH.
6. Run pipx ensurepath again and relogin will fix this. 

**Result**

Can't use gpustack command in shell by default. 

**Environment**

- GPUStack version: v0.2.1 with current installation script. 
- OS: Ubuntu 22.04

**Comment by pengjiang80** [comment]
Update: another impact of this issue is gpustack service will not start after installation, because the command path in gpustack.service is empty in this case.

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(8d3beb5)
- OS: Ubuntu 22.04

**Test Result:** pass
