### ISSUE TITLE
Failed to deploy models on RHEL 8.x

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#290]
**Describe the bug**

**Steps to reproduce**

1. Run GPUStack on RHEL 8.5
2. Deploy a model

**Result**

<img width="2513" alt="image" src="https://github.com/user-attachments/assets/e36eeb60-0917-45e9-9f6c-ef09ae306238">

**Expected behavior**

**Environment**

- GPUStack version: v0.2.1
- OS: RHEL 8.5

**Additional context**

**Comment by thxCode** [comment]
can you retry with llama-box v0.0.55? choice the rockylinux or centos distro release artifact according to your backend.

**Comment by Finenyaco** [comment]
**Environment:**
- GPUStack version: main 74d5e7c
- OS: Red Hat Enterprise Linux release 8.10 (Ootpa)
- GPU: NVIDIA T4

- llama-box version
```
(base) [root@ip-10-0-1-135 ~]# /root/.local/share/pipx/venvs/gpustack/lib/python3.12/site-packages/gpustack/third_party/bin/llama-box/llama-box-linux-amd64-cuda-12.4 --version
version: 7 (Core) (5f77b6c)
llama.cpp version: 1 (1b2f992)
built with cc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2) for x86_64-redhat-linux
```

**Test Result:** pass

<img width="2052" alt="image" src="https://github.com/user-attachments/assets/3ac2f0d7-7741-4577-b41f-ad0de1cca732">
<img width="2097" alt="image" src="https://github.com/user-attachments/assets/0e425c14-a99f-4f6e-98e7-a2f637e476b9">
