### ISSUE TITLE
Support Ascend 910b NPU

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#300]
Support Ascend 910b NPU:
- fastfetch
- llama-box
- gpustack

**Comment by pengjiang80** [comment]
A quick test in Luchentech Ascend 910B environment. Fastfetch 2.5 can't get detailed information of the GPU.

(base) root@notebook-c8de5481-02df-43ee-997f-aafe173923af-0:~/.local/share/pipx/venvs/gpustack/lib/python3.10/site-packages/gpustack/third_party/bin# ./fastfetch/fastfetch-linux-aarch64 --gpu-detection-method pci --gpu-driver-specific true --gpu-temp true      
                             ....              root@notebook-c8de5481-02df-43ee-997f-aafe173923af-0
              .',:clooo:  .:looooo:.           ----------------------------------------------------
           .;looooooooc  .oooooooooo'          OS: Ubuntu focal 20.04 aarch64
        .;looooool:,''.  :ooooooooooc          Host: AT800 (Model 9000) A2
       ;looool;.         'oooooooooo,          Kernel: Linux 5.4.0-26-generic
      ;clool'             .cooooooc.  ,,       Uptime: 15 days, 12 hours, 25 mins
         ...                ......  .:oo,      Packages: 541 (dpkg)
  .;clol:,.                        .loooo'     Shell: bash 5.0.17
 :ooooooooo,                        'ooool     Display (VGA-1): 800x600
'ooooooooooo.                        loooo.    Terminal: /dev/pts/3
'ooooooooool                         coooo.    CPU: TaiShan-v110*192 (192) @ 2.60 GHz
 ,loooooooc.                        .loooo.    GPU: Huawei Technologies Co., Ltd. iBMC Intelligent Management system chip w/VGA support
   .,;;;'.                          ;ooooc     Memory: 19.00 GiB / 1005.62 GiB (2%)
       ...                         ,ooool.     Swap: Disabled
    .cooooc.              ..',,'.  .cooo.      Disk (/): 334.55 GiB / 1006.93 GiB (33%) - overlay
      ;ooooo:.           ;oooooooc.  :l.       Local IP (eth0): 10.42.130.103/32
       .coooooc,..      coooooooooo.           Locale: C
         .:ooooooolc:. .ooooooooooo'
           .':loooooo;  ,oooooooooc                                    
               ..';::c'  .;loooo:'

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main (e5ce7d9)
- OS: Ubuntu 20.04.6 LTS
- GPU: 910B3, CANN 8.0-rc3-alpha2


**Test Result:**

1. Check the GPU list
<img width="2296" alt="image" src="https://github.com/user-attachments/assets/7ad51a01-90a0-47fb-8968-36ee47e06dd5">

2. Deploy models and chat
<img width="2313" alt="image" src="https://github.com/user-attachments/assets/a1a534ff-4d7f-450f-b5c9-631611cd6c32">


**Note:**  [llama.cpp for CANN](https://github.com/ggerganov/llama.cpp/blob/master/docs/backend/CANN.md#model-supports)
