### ISSUE TITLE
Failed to deploy a models using vllm: User-specified max_model_len (8192) is greater than the derived max_model_len

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#313]
**Describe the bug**

Failed to deploy a models using vllm: User-specified max_model_len (8192) is greater than the derived max_model_len

**Steps to reproduce**

1. Deploy the model `Salesforce/blip2-opt-2.7b` from Hugging Face.
2. View the instance logs.

**Result**

<img width="2486" alt="image" src="https://github.com/user-attachments/assets/815e7cf1-1f08-48ac-ba49-dbe910b61848">

**Expected behavior**

**Environment**

- GPUStack version: main
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4090

**Additional context**

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(c8e8485)
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4090

**Test Result:** pass

**Comment by gitlawr** [comment]
Now we cannot run Phi-3.5-vision-instruct with the default setting on a 16GiB card due to the 128k context. We may still want a reasonable default so that it runs easier out of the box.

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(447ac69)
- OS: Ubuntu 22.04
- GPU: NVIDIA GeForce RTX 4080

**Test Result:** pass

```
root      765559 47.0  0.9 4798876 627544 ?      Sl   09:04   0:03 /home/sophia/.local/share/pipx/venvs/gpustack/bin/python /home/sophia/.local/share/pipx/venvs/gpustack/bin/vllm serve /var/lib/gpustack/cache/huggingface/models--Salesforce--blip2-opt-2.7b/snapshots/51572668da0eb669e01a189dc22abe6088589a24 --chat-template=/home/sophia/Downloads/template_blip2.jinja --host 0.0.0.0 --port 41019 --served-model-name blip2-opt-2.7b --trust-remote-code --tensor-parallel-size 2
```

```
root      765255 33.0  0.9 4790764 619388 ?      Sl   09:03   0:03 /home/sophia/.local/share/pipx/venvs/gpustack/bin/python /home/sophia/.local/share/pipx/venvs/gpustack/bin/vllm serve /var/lib/gpustack/cache/huggingface/models--microsoft--Phi-3.5-vision-instruct/snapshots/4a0d683eba9f1d0cbfb6151705d1ee73c25a80ca --max-model-len 8192 --host 0.0.0.0 --port 40604 --served-model-name phi-3.5-vision-instruct --trust-remote-code
```
