### ISSUE TITLE
The model deployed on Windows with CPU offloading has a low token throughput

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#325]
**Describe the bug**

**Steps to reproduce**

1. Install GPUStack on a windows host without GPU.
2. Deploy a model.

**Result**

1. The model deployed through GPUStack has a low throughput
<img width="2560" alt="image" src="https://github.com/user-attachments/assets/d402d294-54ca-445a-906d-b36d639196ca">

2. Manually deploying the same model through llama-box results in normal throughput
<img width="634" alt="image" src="https://github.com/user-attachments/assets/4aa7f05b-0c17-41fb-b95c-275e33d45a94">

**Expected behavior**

**Environment**

- GPUStack version: main(c8e8485)
- OS: Windows 11 pro
- Architecture: ARM64

**Additional context**

**Comment by Finenyaco** [comment]
**GPUStack version**: 52738508c5bcb0d7a8a322efac6f4a7e4d02ddcd

**Test Result:** 
Throughput has improved, but the 'realtime' process priority could cause the system to hang temporarily when using pure CPU for inference.

**Comment by aiwantaozi** [comment]
tps test result:
- qwen2 14b
gpustack realtime high 10.4, temporarily hang
gpustack above high 8.59
box normal 6
box above high 8

- qwen2 7b
gpustack realtime high 21.51, temporarily hang
gpustack above high 17.74
box normal 10.6
box above high 16.5

above high is acceptable, use it.

**Comment by Finenyaco** [comment]
Verified on main (a332695)
