### ISSUE TITLE
Compare UI is blank when there's no models available

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#329]
**Is your enhancement related to a problem? Please describe.**
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/bfce5926-0454-49b6-879f-b000b28d7e51">

**Describe the solution you'd like**

Provide info telling no available models or guide users to deploy models.

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(447ac69)
- UI version: 5c2503b
- OS: macOS 14.6.1
- GPU: Apple M2, 24G

**Test Result:** pass
