### ISSUE TITLE
The label added to the model is incorrect

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#332]
**Describe the bug**
The label auto added to the model is incorrect:

<img width="525" alt="image" src="https://github.com/user-attachments/assets/f2dbb962-18f1-4c4a-b121-b4986c2a3b34">
<img width="1257" alt="image" src="https://github.com/user-attachments/assets/d859a6ba-293f-4a96-82d0-b0f7b57229bb">

**Steps to reproduce**

Deploy model and use the vllm backend.

- GPUStack version: 71a49fd

**Comment by linyinli** [comment]
The label ‘os:linux’ is also incorrect, the correct worker label is ‘os:Linux’.

**Comment by gitlawr** [comment]
Those are legacy labels before we support label selectors

**Comment by linyinli** [comment]
It worked after editing the worker labels.
