### ISSUE TITLE
Support deploy model in windows Arm64

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#349]
**Is your enhancement related to a problem? Please describe.**

Now running gpustack in Windows arm then deploy model, will use llama-box-amd64-avx2.exe, which is for amd64, by default windows emulation should handle the emulate from amd64 to arm64, but seems like this binary couldn't work with Windows emulation, so it would be better could use llama-box-arm64-neon.exe

**Additional context**
Device: DELL XPS 13 9345 (Snapdragon X Elite X1E80100)
Windows Arm64
gpustack version: https://github.com/gpustack/gpustack/commit/74d5e7cfdb09de080b492b49e053c3d93d5e0892

**Comment by gitlawr** [comment]
To investigate:
When running llama-box-arm64-neon with Qwen2.5-0.5B-q4-k_m, it exits without any error:
```
.....................................................
0.00.786.568 I llama_new_context_with_model: n_ctx      = 8192
0.00.786.593 I llama_new_context_with_model: n_batch    = 2048
0.00.786.593 I llama_new_context_with_model: n_ubatch   = 512
0.00.786.593 I llama_new_context_with_model: flash_attn = 0
0.00.786.596 I llama_new_context_with_model: freq_base  = 1000000.0
0.00.786.597 I llama_new_context_with_model: freq_scale = 1
0.00.822.524 I llama_kv_cache_init:        CPU KV buffer size =    96.00 MiB
0.00.822.550 I llama_new_context_with_model: KV self size  =   96.00 MiB, K (f16):   48.00 MiB, V (f16):   48.00 MiB
0.00.822.558 I llama_new_context_with_model:        CPU  output buffer size =     0.02 MiB
0.00.824.925 I llama_new_context_with_model:        CPU compute buffer size =   300.25 MiB
0.00.824.934 I llama_new_context_with_model: graph nodes  = 846
0.00.824.935 I llama_new_context_with_model: graph splits = 1
0.00.824.938 W llama_init_from_gpt_params: warming up the model with an empty run - please wait ... (--no-warmup to disable)
```

Notes:
1. 1.5b works.
2. q2_k works.

**Comment by Finenyaco** [comment]
Verified on main 81cf069

llama-box version:
```
version: v0.0.65 (9be586a)
llama.cpp version: 3934 (3752217e)
built with MSVC 19.41.34120.0 for ARM64
```
