### ISSUE TITLE
The embedding model with vLLM backend does not have the “Embedding Only” tag

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#367]
Model: intfloat/e5-mistral-7b-instruct
<img width="1644" alt="image" src="https://github.com/user-attachments/assets/8d7aa4b1-d16f-441a-bc35-8ceda6d10383">

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(b805d00)

**Test Result:** pass

Only embedding models based on the "Gemma2Model" and "MistralModel" architectures are supported now. https://docs.vllm.ai/en/latest/models/supported_models.html#text-embedding

<img width="2077" alt="image" src="https://github.com/user-attachments/assets/04797ab6-783d-446c-a9ca-1418ee329938">
