### ISSUE TITLE
When I configure proxy in the env, gpustack seems to be unable to access the local interface

### ISSUE THREAD

**Issue by lijia15x** [gpustack/gpustack#373]
when I set http_proxy/https_proxy/no_proxy

after gpustack start, log shows：

 <p> The webserver reported that an error occurred while trying to access the website. Please return to the previous page. </p> <table> <tbody> <tr> <td> URL </td> <td> http://127.0.0.1:81/v1/workers?name=ai-server01 (127.0.0.1) </td> </tr> <td><b>Proxy: </b> </td> <td> shzproxy101 </td></tbody> </table> </div> </body></html>\r\n'
Error running watch_model_instances: Failed to get current worker id

how to fix this?

OS: ubuntu22.04

**Comment by lijia15x** [comment]
remove the proxy will fix the issue, but I can not download llm through gpustack

**Comment by gitlawr** [comment]
Did you set `127.0.0.1` or any other address for GPUStack server in `no_proxy`?

**Comment by lijia15x** [comment]
no_proxy=10.0.0.0/8,192.168.0.0/16,localhost,127.0.0.0/8,134.134.0.0/16,172.16.0.0/20   this is what I set

**Comment by lijia15x** [comment]
I set no_porxy=127.0.0.1, then the issue fixed
