### ISSUE TITLE
"Cannot find the requested files in the cached path" error when deploying multi-file gguf model with distributed inference 

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#377]
Version: 0.3.0
Environment: DAModel with 2 x 4090 
Step to reproduce:
1. Use modelscope to deploy qwen2.5-14b-instruct-gguf and chose FP16, which has 8 files.
2. GPUStack will download the file and the download repeat issue may also appear.
3. Finally it will show "Failed to download model: Cannot find the requested files in the cached path and outgoing traffic has been disabled. To enable look-ups and downloads online, set 'local_files_only' to False."
4. Tried to delete model instance and it doesn't help.
5. It will also redownload the last model file although it's already there.
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/fbc7c9c4-f794-4fcd-9280-5bae197ace4e">
<img width="1302" alt="image" src="https://github.com/user-attachments/assets/ea984a87-6365-469c-9335-3b3cb55996bb">

**Comment by gitlawr** [comment]
Duplicate with https://github.com/gpustack/gpustack/issues/361
