### ISSUE TITLE
download progress in instance logs looks strange

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#382]
**Describe the bug**

![image](https://github.com/user-attachments/assets/7c624e84-10d3-4b7b-9cf9-a6d05152e5df)
![image](https://github.com/user-attachments/assets/0cce3194-6eb5-438d-b5f2-1eccd3a17ef7)

**Steps to reproduce**

1. Deploy Qwen/Qwen2.5-14B-Instruct-GGUF, qwen2.5-14b-instruct-q2_k-*.gguf
2. View instance logs

**Environment**

- GPUStack version: 0.3.0

**Comment by Finenyaco** [comment]
**UI version:** 57386ee

**Test Result:** pass
<img width="1151" alt="image" src="https://github.com/user-attachments/assets/19c816c6-63a9-4054-82e3-b01ba444766b">
