### ISSUE TITLE
docker运行时cuda版本必须大于等于12.5？？

### ISSUE THREAD

**Issue by guoshiyin-666** [gpustack/gpustack#399]
Attaching to ubuntu-gpustack-1
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: requirement error: unsatisfied condition: cuda>=12.5, please update your driver to a newer version, or use an earlier cuda container: unknown

**Comment by gitlawr** [comment]
What's your driver version and runtime version?

**Comment by guoshiyin-666** [comment]
> 您的驱动程序版本和运行时版本是什么？

cuda 12.0

**Comment by gitlawr** [comment]
Can you run nvidia-smi to check the driver version?
Is it feasible to update the driver to a version compatible with CUDA `12.5.1` according to the information provided at https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id5?

**Comment by guoshiyin-666** [comment]
> 您可以运行 nvidia-smi 来检查驱动程序版本吗？根据https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id5提供的信息 ，将驱动程序更新为与 CUDA 兼容的版本是否可行？`12.5.1`[](https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id5)

只能通过更新cuda版本才能解决这个问题吗？可不可以构建的时候降低构建镜像的初始版本，或者是通过修改一些docker的配置解决呢？

**Comment by gitlawr** [comment]
GPUStack can work with CUDA 12.0, the official docker image is built with 12.5.1.
For 0.3.0:
Option 1: update the driver
Option 2: Build your image with a custom [CUDA_VERSION](https://github.com/gpustack/gpustack/blob/main/Dockerfile#L1)

We will evaluate whether we should change the built-in version in the official image to ensure broader compatibility.

**Comment by guoshiyin-666** [comment]
# cuda版本替换了12.0
ARG CUDA_VERSION=12.0.0

FROM dockerpull.com/nvidia/cuda:$CUDA_VERSION-runtime-ubuntu22.04

ARG TARGETPLATFORM
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    wget \
    tzdata \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

COPY dist/*.whl /tmp/

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    echo "Installing x86_64 wheel"; \
    pip3 install /tmp/*_x86_64.whl vllm; \
    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    echo "Installing aarch64 wheel"; \
    pip3 install /tmp/*_aarch64.whl; \
    else \
    echo "Unsupported platform: $TARGETPLATFORM"; \
    fi \
    && rm /tmp/*.whl

ENTRYPOINT [ "gpustack", "start" ]


# 构建启动
docker-compose up
WARN[0000] Found orphan containers ([gpustack-gpustack-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
Attaching to gpustack-gpustacks-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gpustack": executable file not found in $PATH: unknown

还是不行啊

**Comment by guoshiyin-666** [comment]
> GPUStack 可以与 CUDA 12.0 配合使用，官方 docker 镜像是用 12.5.1 构建的。 对于 0.3.0： 选项 1：更新驱动程序选项 2：使用自定义[CUDA_VERSION](https://github.com/gpustack/gpustack/blob/main/Dockerfile#L1) 构建镜像[](https://github.com/gpustack/gpustack/blob/main/Dockerfile#L1)
> 
> 我们将评估是否应该更改官方图像中的内置版本以确保更广泛的兼容性。

# cuda版本替换了12.0
ARG CUDA_VERSION=12.0.0

FROM dockerpull.com/nvidia/cuda:$CUDA_VERSION-runtime-ubuntu22.04

ARG TARGETPLATFORM
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    wget \
    tzdata \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

COPY dist/*.whl /tmp/

RUN if [ "$TARGETPLATFORM" = "linux/amd64" ]; then \
    echo "Installing x86_64 wheel"; \
    pip3 install /tmp/*_x86_64.whl vllm; \
    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
    echo "Installing aarch64 wheel"; \
    pip3 install /tmp/*_aarch64.whl; \
    else \
    echo "Unsupported platform: $TARGETPLATFORM"; \
    fi \
    && rm /tmp/*.whl

ENTRYPOINT [ "gpustack", "start" ]


# 构建启动
docker-compose up
WARN[0000] Found orphan containers ([gpustack-gpustack-1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
Attaching to gpustack-gpustacks-1
Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "gpustack": executable file not found in $PATH: unknown

还是不行啊

**Comment by gitlawr** [comment]
```
# Example Dockerfile
ARG CUDA_VERSION=12.5.1

FROM nvidia/cuda:$CUDA_VERSION-runtime-ubuntu22.04

ARG TARGETPLATFORM
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    wget \
    tzdata \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*


RUN pip3 install gpustack[vllm] && \
    pip3 cache purge

ENTRYPOINT [ "gpustack", "start" ]
```
Example build:
```
docker build -t my/gpustack:0.3.0 --build-arg CUDA_VERSION=12.0.0 .
```
