### ISSUE TITLE
Show huggingface model name instead of file name in model list page

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#405]
**Is your enhancement related to a problem? Please describe.**

Huggingface source looks inconsistent

<img width="1259" alt="image" src="https://github.com/user-attachments/assets/df70c37a-b442-4663-83ab-c03fadf37af7">

**Describe the solution you'd like**

Show `Hugging Face/Qwen/Qwen2.5-0.5B-Instruct-GGUF` and `Hugging Face/Qwen/Qwen2.5-0.5B-Instruct` for the above cases

**Comment by Finenyaco** [comment]
**UI version:** b9c9fe7

<img width="1191" alt="image" src="https://github.com/user-attachments/assets/1634ab4c-f37b-4c8a-a14b-ca98970968b0">
