### ISSUE TITLE
Support HF_ENDPOINT variable 

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#419]
HF_ENDPOINT environment variable can be used to connect to private Hub or mirror in China. We should support this configuration.

**Comment by pengjiang80** [comment]
Related to https://github.com/gpustack/gpustack/issues/413

**Comment by Finenyaco** [comment]
**GPUStack version:** main 926f2ee

**Issue 1:** The filter does not take effect.

<img width="793" alt="image" src="https://github.com/user-attachments/assets/fe487f9d-1a29-4391-b959-a72c155dbb97">


**Issue 2:** Failed to fetch the README.md file.

<img width="2346" alt="image" src="https://github.com/user-attachments/assets/9e053ace-b10b-4d46-8d8c-e4cd64b37382">

**Comment by Finenyaco** [comment]
**GPUStack version:** df21c4b
**UI version:** c8c22b3

**Issue 1:** Failed, the search results are still incorrect.
**Issue 2:** Cannot view the images.

<img width="756" alt="image" src="https://github.com/user-attachments/assets/718a5f2a-a4d7-4e95-b3c3-c2299caf5743">


**Issue 3:** Environment variables set in /etc/default/gpustack are not taking effect on macOS.

**Comment by Finenyaco** [comment]
**GPUStack version:** fbb5359
**UI version:** 961d420

**Test Result:**

When GPUStack is installed on a Ubuntu host, it fails to get the model list from hf-mirror.com

<img width="2337" alt="image" src="https://github.com/user-attachments/assets/9e78489c-1215-4500-8223-2e8212bff605">

<img width="1922" alt="image" src="https://github.com/user-attachments/assets/e7c99bac-247f-4c9b-89df-ee115e04a3fc">

**Comment by Finenyaco** [comment]
Verified  on main 1c069f3
