### ISSUE TITLE
Chat failed: 'msg': 'Extra inputs are not permitted', 'input': {'include_usage': True}

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#429]
**Describe the bug**

**Steps to reproduce**

1. Deploy a model using the vllm inference engine. e.g. Hugging Face/Qwen/Qwen2.5-0.5B-Instruct
2. Go the playground and chat.

**Result**

1. Returned an error: `[{'type': 'extra_forbidden', 'loc': ('body', 'stream_otpions'), 'msg': 'Extra inputs are not permitted', 'input': {'include_usage': True}}]`

<img width="1942" alt="image" src="https://github.com/user-attachments/assets/9f83787a-1f26-4806-a275-66a30fcaf39f">

<img width="769" alt="image" src="https://github.com/user-attachments/assets/dccbae3b-4938-49b8-9c2a-b26e6046499c">

**Expected behavior**

**Environment**

- GPUStack version: 73e7a13
- UI version: eb5cf9d

**Additional context**

**Comment by gitlawr** [comment]
Fix the typo `stream_otpions`

**Comment by Finenyaco** [comment]
**UI version:**  c442a33

**Test Result:** pass

<img width="2344" alt="image" src="https://github.com/user-attachments/assets/e85b7e0b-f86f-4f64-9979-05309905658a">

<img width="776" alt="image" src="https://github.com/user-attachments/assets/df23846d-c8b3-4d46-b019-17f3b2ee2e67">
