### ISSUE TITLE
UI Rewording

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#437]
**Describe the bug**

<img width="730" alt="image" src="https://github.com/user-attachments/assets/6a007030-ff2a-4955-a966-88f5eb1155da">

Change `Distribution Across Workers` to `Distributed Across Workers`

<img width="719" alt="image" src="https://github.com/user-attachments/assets/5facf43e-d350-4b45-aaec-55747265fa01">

IP should not include the port.

**Comment by Finenyaco** [comment]
**UI version:** 8576015

**Test Result:** 


<img width="1404" alt="image" src="https://github.com/user-attachments/assets/38f33f3f-3d4e-474d-a240-011ad610aae9">

<img width="1328" alt="image" src="https://github.com/user-attachments/assets/1891bd90-5b57-4595-a819-8230aba6a5a0">

**Comment by Finenyaco** [comment]
**UI version:** 90350f9

**Test Result:** pass
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/4d2db9b6-397e-4ed2-a3a6-e7f65b588187">
<img width="945" alt="image" src="https://github.com/user-attachments/assets/34421ef9-c19a-4580-8739-a71be13539e4">
