### ISSUE TITLE
The instance status is "Running" with message "No suitable workers"

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#445]
**Describe the bug**

**Steps to reproduce**

1. Deploy a non-gguf model.
2. Check the instance status.

**Result**

1. Occasionally, it may display "No suitable workers," even though the model has been successfully deployed.

<img width="2060" alt="image" src="https://github.com/user-attachments/assets/251e969f-0238-4194-8926-6faba784fb42">

<img width="1087" alt="image" src="https://github.com/user-attachments/assets/dc90198a-24e0-489f-9e36-d64b51683ce4">

**Expected behavior**

**Environment**

- GPUStack version: main fbae4d3
- OS: Ubuntu 22.04 
- GPU: NVIDIA GeForce RTX 4090

**Additional context**

**Comment by gitlawr** [comment]
Hopefully fixed on main. Please reopen if that's not the case
