### ISSUE TITLE
Worker IP changed, model instance endpoint not updated

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#460]
**Describe the bug**

**Steps to reproduce**

1. Deploy a model
2. Change the worker IP address from 1921.68.50.123 to 192.168.50.125
3. Check the worker list
4. Check the model instance endpoint

**Result**

1. Worker IP has been updated
<img width="952" alt="image" src="https://github.com/user-attachments/assets/ba74d192-5a43-441c-b538-9877c7c09263">

2. The instance endpoint has not been updated
<img width="1075" alt="image" src="https://github.com/user-attachments/assets/543d4226-2bc4-4c48-a8be-31fe2cefaaaa">

3.  Failed to chat. Re-deploy the instance is required.

<img width="1900" alt="image" src="https://github.com/user-attachments/assets/e7d6fd5e-70cf-4560-950b-e159411edf7f">

**Expected behavior**

**Environment**

- GPUStack version: main 67453bc
- OS: macOS 15.1
- GPU: Apple M2

**Additional context**

**Comment by gitlawr** [comment]
`'MetricExporter' object has no attribute '_collector'` in `https://github.com/gpustack/gpustack/blob/main/gpustack/worker/worker.py#L191`

**Comment by Finenyaco** [comment]
Verified on main 4573aae
