### ISSUE TITLE
Support Tool calling in llama-box

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#489]
Tool calling is a key requirement for AI agents. We need to support tool calling.

**Comment by verigle** [comment]
however vllm not support distribute deploy, llama-box support distribute deploy, but not support Tool calling,
is there any plan to support  Tool calling for  llama-box with distribute  deploy?

**Comment by gitlawr** [comment]
There are ongoing work in the llama.cpp upstream and we are keeping track of it.
We are planning to investigate vLLM distributed deployment via https://github.com/gpustack/gpustack/issues/750.

**Comment by verigle** [comment]
ollama deploy qwen2.5:72b can use tool very well, but using gpustack with llama-box to deploy qwen2.5:72b(downloading source: ollama) can not using tool
I test it on a dify agent app, how to solve it?

**Comment by gitlawr** [comment]
It needs to be addressed via https://github.com/gpustack/gpustack/issues/751

**Comment by gitlawr** [comment]
We are investigating whether we should support this in llama-box to make it easier for users in most cases.

**Comment by Finenyaco** [comment]
Verified in main 37cc489, llama-box version v0.0.97

Known issues: 
[The Granite model failed to use tool calling](https://github.com/gpustack/llama-box/issues/16)
[Incorrect responses when using toolcalling with a specified seed](https://github.com/gpustack/llama-box/issues/17)

**Comment by Finenyaco** [comment]
Verified in llama-box v0.0.98
