### ISSUE TITLE
Show more information for model deployment in pending status with vLLM backend 

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#491]
Version: v0.3.1
Step to reproduce:
1. Try to deploy a model that exceeds the GPU VRAM.
2. The model instance will be in pending status but didn't show more helpful information. 
3. For llama.cpp, it will show no suitable worker.
4. GPUStack log file just showed scheduling info and didn't show additional information.

**Comment by pengjiang80** [comment]
As resource calculation is not very straightforward and clear for most users. It's better to consider adding more hint in this scenario. Including:
1. Let users know vLLM requires Linux worker.
2. vLLM has a default gpu_memory_utilization as 0.9 and almost require an free GPU card and can be adjusted. 
These two can be added to pending message hint and will be more friendly to users not familiar with vLLM. 
3. More information in GPUStack documentation to let users know how we calculate vRAM requirements with vLLM backend.

**Comment by Finenyaco** [comment]
Verified on main e4a7bf3

<img width="1498" alt="image" src="https://github.com/user-attachments/assets/50ce0b8a-0d6d-4f59-ba7b-a8fe6f8f8694">

<img width="2105" alt="image" src="https://github.com/user-attachments/assets/3e145624-8468-445d-b888-68609c1cc0ac">
