### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'terminate'

### ISSUE THREAD

**Issue by xlshao2021** [gpustack/gpustack#493]
Unable to start GPUStack on command line on Mac & Linux.

**Steps to reproduce**

1. install using pip install gpustack

2. Run gpustack start
2024-10-29T00:29:24+08:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-10-29T00:29:24+08:00 - gpustack.server.server - INFO - Running database migration.
2024-10-29T00:29:24+08:00 - gpustack.cmd.start - CRITICAL - (sqlite3.OperationalError) no such column: "memory"
[SQL: ALTER TABLE system_loads RENAME memory TO ram]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-10-29T00:29:24+08:00 - gpustack.server.server - INFO - Stopping GPUStack server.
Exception ignored in atexit callback: <bound method Server.at_exit of <gpustack.server.server.Server object at 0x7fdc2ed97fd0>>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/gpustack/lib64/python3.11/site-packages/gpustack/server/server.py", line 204, in at_exit
    process.terminate()
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 133, in terminate
    self._popen.terminate()
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'terminate'

**Environment**

- GPUStack version: 0.3.1
- OS: Mac 13.6.6, Linux x86_64
- GPU: intel iris plus graphics 640 on Mac, A10 on Linux

**Comment by gitlawr** [comment]
Could you run the following command and provide the output to help us diagnose?

1. Create `debug_db.py` with:
```
import sqlite3

db_path = '/var/lib/gpustack/database.db'
conn = sqlite3.connect(db_path)
cursor = conn.cursor()
cursor.execute("SELECT version_num FROM alembic_version")
version_num = cursor.fetchone()

if version_num:
    print("Current Alembic version:", version_num[0])
else:
    print("alembic_version not found")

cursor.execute("PRAGMA table_info(system_loads)")
schema_info = cursor.fetchall()

print("system_loads schema:")
for column in schema_info:
    print(f"Column: {column[1]}, type: {column[2]}, nullable: {bool(column[3])}, default: {column[4]}")

conn.close()
```

2. Run `python debug_db.py`

**Comment by xlshao2021** [comment]
Here's the output on the Linux box:

Current Alembic version: 8277680cfcb7
system_loads schema:
Column: id, type: INTEGER, nullable: True, default: None
Column: timestamp, type: INTEGER, nullable: True, default: None
Column: cpu, type: FLOAT, nullable: False, default: None
Column: ram, type: FLOAT, nullable: False, default: None
Column: gpu, type: FLOAT, nullable: False, default: None
Column: vram, type: FLOAT, nullable: False, default: None

**Comment by gitlawr** [comment]
Does the issue persist if you run `gpustack start` again?
Does the issue persist if you try again after removing `/var/lib/gpustack/database.db`?

**Comment by xlshao2021** [comment]
Right, same error message even after I delete the database.db file

**Comment by gitlawr** [comment]
We are investigating a reproducible way to replicate the issue.
Is there any specific reason you prefer installing GPUStack manually using pip rather than using the install script?
Could you please share the existing packages from `pip list`?

**Comment by xlshao2021** [comment]
Well, I don't have any preferences. It just failed as well for manual installation. I attached the error message here (
[error.txt](https://github.com/user-attachments/files/17550907/error.txt)) for your reference.

The output of pip list:
Package                 Version
----------------------- -----------
aiosqlite               0.20.0
alembic                 1.13.3
anaconda-anon-usage     0.4.4
annotated-types         0.7.0
anyio                   4.6.2.post1
APScheduler             3.10.4
archspec                0.2.3
argon2-cffi             23.1.0
argon2-cffi-bindings    21.2.0
asyncer                 0.0.8
asyncpg                 0.29.0
attrs                   23.2.0
boltons                 23.0.0
Brotli                  1.0.9
certifi                 2024.8.30
cffi                    1.17.1
charset-normalizer      3.3.2
click                   8.1.7
colorama                0.4.6
conda                   24.9.2
conda-content-trust     0.2.0
conda-libmamba-solver   24.9.0
conda-package-handling  2.3.0
conda_package_streaming 0.10.0
cryptography            43.0.0
dataclasses-json        0.6.7
distro                  1.9.0
fastapi                 0.115.4
fastapi-cdn-host        0.8.1
filelock                3.16.1
frozendict              2.4.2
fsspec                  2024.10.0
gpustack                0.3.1
greenlet                3.1.1
h11                     0.14.0
httpcore                1.0.6
httpx                   0.27.2
huggingface-hub         0.23.5
idna                    3.7
importlib_resources     6.4.5
inflection              0.5.1
iniconfig               2.0.0
jiter                   0.6.1
jsonpatch               1.33
jsonpointer             2.1
libmambapy              1.5.8
Mako                    1.3.6
MarkupSafe              3.0.2
marshmallow             3.23.0
menuinst                2.1.2
modelscope              1.19.2
mypy-extensions         1.0.0
numpy                   2.1.2
openai                  1.52.2
packaging               24.1
pip                     24.2
platformdirs            3.10.0
pluggy                  1.5.0
prometheus_client       0.20.0
psutil                  5.9.8
pycosat                 0.6.6
pycparser               2.21
pydantic                2.9.2
pydantic_core           2.23.4
pydantic-settings       2.6.0
PyJWT                   2.9.0
PySocks                 1.7.1
pytest                  8.3.3
pytest-asyncio          0.23.8
python-dotenv           1.0.1
python-multipart        0.0.9
pytz                    2024.2
PyYAML                  6.0.2
regex                   2024.9.11
requests                2.32.3
ruamel.yaml             0.18.6
ruamel.yaml.clib        0.2.8
safetensors             0.4.5
setproctitle            1.3.3
setuptools              75.1.0
shellcheck-py           0.10.0.1
six                     1.16.0
sniffio                 1.3.1
socksio                 1.0.0
SQLAlchemy              2.0.36
sqlmodel                0.0.18
starlette               0.41.2
tokenizers              0.20.1
tqdm                    4.66.5
transformers            4.46.0
truststore              0.9.2
typing_extensions       4.12.2
typing-inspect          0.9.0
tzdata                  2024.2
tzlocal                 5.2
urllib3                 2.2.3
uvicorn                 0.30.6
wheel                   0.44.0
zstandard               0.23.0

**Comment by dantegarden** [comment]
I have the same issue
```~# gpustack start --host 0.0.0.0 --port 8721 --bootstrap-password oneflow@123456
2024-10-29T17:03:10+08:00 - gpustack.server.server - INFO - Starting GPUStack server.
2024-10-29T17:03:10+08:00 - gpustack.server.server - INFO - Running database migration.
2024-10-29T17:03:12+08:00 - gpustack.cmd.start - CRITICAL - (sqlite3.OperationalError) near "DROP": syntax error
[SQL: ALTER TABLE model_instances DROP COLUMN gpu_index]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
2024-10-29T17:03:12+08:00 - gpustack.server.server - INFO - Stopping GPUStack server.
Exception ignored in atexit callback: <bound method Server.at_exit of <gpustack.server.server.Server object at 0x7f1590fcaa40>>
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/gpustack/lib/python3.10/site-packages/gpustack/server/server.py", line 204, in at_exit
    process.terminate()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 133, in terminate
    self._popen.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'

**Comment by gitlawr** [comment]
@dantegarden Can you provide your context:
1. Fresh install / upgrade ?
2. Env
3. Steps before getting the error

**Comment by xlshao2021** [comment]
Uninstall both versions, then reinstall using the script, still reports error messages, please refer to the attached file
[output.txt](https://github.com/user-attachments/files/17555092/output.txt):
#sudo /var/lib/gpustack/uninstall.sh
#pip uninstall gpustack
#curl -sfL https://get.gpustack.ai | sh -s - --port 443
# gpustack chat llama3.2 "tell me a joke."
Request to server failed: (404, 'Unknown', ...

Thx

> ```
> # Logs from error.txt
> gpustack chat llama3.2 "tell me a joke."
> Request to server failed: (404, 'Unknown', '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">\n\n<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">\n    <head>\n        <title>The page is not found</title>\n        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n        <style type="text/css">\n            /*<![CDATA[*/\n            body {\n                background-color: #fff;\n                color: #000;\n                font-size: 0.9em;\n                font-family: sans-serif,helvetica;\n                margin: 0;\n                padding: 0;\n            }\n            :link {\n                color: #c00;\n            }\n            :visited {\n                color: #c00;\n            }\n            a:hover {\n                color: #f50;\n            }\n            h1 {\n                text-align: center;\n                margin: 0;\n                padding: 0.6em 2em 0.4em;\n                background-color: #f73;\n                color: #fff;\n                font-weight: normal;\n                font-size: 1.75em;\n                border-bottom: 2px solid #000;\n            }\n            h1 strong {\n                font-weight: bold;\n                font-size: 1.5em;\n            }\n 
>       h2 {\n                text-align: center;\n                background-color: #f73;\n                font-size: 1.1em;\n                font-weight: bold;\n                color: #fff;\n                margin: 0;\n                padding: 0.5em;\n                border-bottom: 2px solid #000;\n            }\n            h3 {\n                text-align: center;\n                background-color: #8B6969;\n                padding: 0.5em;\n                color: #fff;\n            }\n            hr {\n                display: none;\n            }\n            .content {\n                padding: 1em 5em;\n            }\n            .alert {\n                border: 2px solid #000;\n            }\n\n            img {\n                border: 2px solid #fff;\n                padding: 2px;\n                margin: 2px;\n            }\n            a:hover img {\n                border: 2px solid #294172;\n            }\n            .logos {\n                margin: 1em;\n                text-align: center;\n            }\n            /*]]>*/\n        </style>\n    </head>\n\n    <body>\n        <h1><strong>nginx error!</strong></h1>\n\n        <div class="content">\n\n            <h3>The page you are looking for is not found.</h3>\n\n            <div class="alert">\n                <h2>Website Administrator</h2>\n                <div class="content">\n  
>       <p>Something has triggered missing webpage on your\n                    website. This is the default 404 error page for\n                    <strong>nginx</strong> that is distributed with\n                    Anolis OS.  It is located\n                    <tt>/usr/share/nginx/html/404.html</tt></p>\n\n                    <p>You should customize this error page for your own\n                    site or edit the <tt>error_page</tt> directive in\n                    the <strong>nginx</strong> configuration file\n                    <tt>/etc/nginx/nginx.conf</tt>.</p>\n\n                    <p>For information on Anolis OS, please visit the <a href="https://openanolis.cn/">OpenAnolis Community</a>. The documentation for Anolis OS is <a href="https://openanolis.cn/">available on the OpenAnolis Community website</a>.</p>\n\n                </div>\n            </div>\n\n            <div class="logos">\n                <a href="http://nginx.net/"><img\n                    src="nginx-logo.png" \n                    alt="[ Powered by nginx ]"\n                    width="121" height="32" /></a>\n                <a href="https://openanolis.cn/"><img\n                    src="poweredby.png"\n                    alt="[ Powered by Anolis OS ]"\n                    width="88" height="31" /></a>\n            </div>\n        </div>\n    </body>\n</html>\n')
> ```
> 
> Initial error from log indicates that the requrest goes to an nginx instead of the GPUStack server. If the default port is occupied, you can customize the port on GPUStack installation:
> 
> ```
> curl -sfL https://get.gpustack.ai | sh -s - --port <your-port>
> ```
> 
> Did you uninstall before running `gpustack start`? We don't expect both a manual run and the systemd service to coexist. If that's the case, could you try uninstalling then reinstalling with the custom port to see if it resolves the issue?
> 
> Example:
> 
> ```
> # uninstall
> sudo /var/lib/gpustack/uninstall.sh
> # reinstall
> curl -sfL https://get.gpustack.ai | sh -s - --port 9999
> ```
> 
> Then follow the instruction to access the UI.
> 
> Reference for using the install script: https://docs.gpustack.ai/installation/installation-script/

**Comment by gitlawr** [comment]
The link for `output.txt` is unavailable for me.

For custom host/port you need to set `GPUSTACK_SERVER_URL=<your-url>` so I suggest checking the UI previously.
Ref: https://docs.gpustack.ai/latest/cli-reference/chat/#connect-to-external-gpustack-server

Can you check if server is running now (`systemctl status gpustack`)

**Comment by xlshao2021** [comment]
Turns out that it is running and can be accessed via a browser. The problem is: how can I find out the default password? There's no such file called initial_admin_password anywhere on my disk...

**Comment by gitlawr** [comment]
It's in `/var/lib/gpustack/initial_admin_password ` by default

**Comment by xlshao2021** [comment]
There's no such file. I searched the whole hard disk and there's no such file.

# sudo ls /var/lib/gpustack/initial_admin_password
ls: cannot access '/var/lib/gpustack/initial_admin_password': No such file or directory

# find / -name initial_admin_password
#

**Comment by gitlawr** [comment]
1. Did you see logs like `Generated initial admin password. You can get it from xxx` in `/var/log/gpustack.log`?
2. What do you see in `ls /var/lib/gpustack`?
3. Alternatively, it can be set by `--bootstrap-password`, e.g, `curl -sfL https://get.gpustack.ai/ | sh -s - --port 443 --bootstrap-password <your-password>`. (note that it's only valid for fresh install so you need to reinstall if you need this flag)

**Comment by xlshao2021** [comment]
Guess I have to re-install it later on, using your latest instructions.

Just FYI:
- There's no initial password in /var/log/gpustack.log
- No initial password printed out when I installed it.
- Here are the files under /var/lib/gpustack: database.db  jwt_secret_key  log  token  uninstall.sh  worker_name
-

**Comment by xlshao2021** [comment]
It didn't go as smoothly as I expected.

I uninstalled it and reboot the Linux machine. Then reinstalled it using command: curl -sfL https://get.gpustack.ai/ | sh -s - --port 443 --bootstrap-password xxx

Even though it said gpustack was running but I was unable to access via web browser. I am copying the terminal output below, and also attached log file here for your reference
[gpustatck.log](https://github.com/user-attachments/files/17558260/gpustatck.log)
.

$ curl -sfL https://get.gpustack.ai/ | sh -s - --port 80 --bootstrap-password 123456
[INFO]  GPUStack is already installed. Upgrading...
pipx >(setup:1110): pipx version is 1.7.1
pipx >(setup:1111): Default python interpreter is '/usr/bin/python3.11'
pipx >(package_name_from_spec:378): Determined package name: gpustack
pipx >(package_name_from_spec:379): Package name determined in 0.0s
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(needs_upgrade:99): Time since last upgrade of shared libs, in seconds: 79211. Upgrade will be run by pipx if greater than 2592000.
pipx >(run_subprocess:175): running <checking pip's availability>
Installing to existing venv 'gpustack'
pipx >(create_venv:164): Creating virtual environment
creating virtual environment...
pipx >(run_subprocess:175): running /usr/bin/python3.11 -m venv --without-pip /root/.local/share/pipx/venvs/gpustack
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /root/.local/share/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python --version
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: gpustack[vllm]
pipx >(install_package:247): Installing gpustack from spec 'gpustack[vllm]'
installing gpustack from spec 'gpustack[vllm]'...
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python -m pip --no-input install --force-reinstall gpustack[vllm]
pipx >(run_subprocess:175): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:351): get_venv_metadata_for_package: 3196ms
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: gpustack[vllm]
pipx >(_symlink_package_resource:132): Force is true. Removing /root/.local/bin/gpustack.
  installed package gpustack 0.3.1, installed using Python 3.11.2
  These apps are now globally available
    - gpustack
done! ✨ 🌟 ✨
[INFO]  Setting up GPUStack as a service using systemd.
Created symlink /etc/systemd/system/multi-user.target.wants/gpustack.service → /etc/systemd/system/gpustack.service.
[INFO]  Upgrade complete. 


$ systemctl status gpustack
● gpustack.service - GPUStack Service
   Loaded: loaded (/etc/systemd/system/gpustack.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2024-10-29 22:13:08 CST; 2s ago
 Main PID: 2630 (pt_main_thread)
    Tasks: 4 (limit: 97236)
   Memory: 366.7M
   CGroup: /system.slice/gpustack.service
           └─2630 /root/.local/share/pipx/venvs/gpustack/bin/python /root/.local/bin/gpust>

Oct 29 22:13:08 iZ2ze4ge7l8kjzp1n3tkr2Z systemd[1]: gpustack.service: Scheduled restart jo>
Oct 29 22:13:08 iZ2ze4ge7l8kjzp1n3tkr2Z systemd[1]: Stopped GPUStack Service.
Oct 29 22:13:08 iZ2ze4ge7l8kjzp1n3tkr2Z systemd[1]: Started GPUStack Service.

**Comment by gitlawr** [comment]
We have verified a db migration [issue](https://github.com/gpustack/gpustack/issues/281) during upgrade, and plan to fix it in next release.

>[INFO] GPUStack is already installed. Upgrading...

From the logs it seems that previous installation is not cleaned up. Can you run `sudo /var/lib/gpustack/uninstall.sh` and verify `/var/lib/gpustack` is removed, then reinstall?

**Comment by xlshao2021** [comment]
yes. /var/lib/gpustack & /var/log/gpustack.log were all gone after running the uninstall script. But that problem is still there. I just don't know why it still tells me Gpustack is already installed...

**Comment by gitlawr** [comment]
It detects the `gpustack` command, which should be removed by the uninstallation script using `pipx uninstall gpustack`. Did the uninstallation succeeded without any error?

**Comment by xlshao2021** [comment]
It claimed that was successful:

# sudo /var/lib/gpustack/uninstall.sh
Traceback (most recent call last):
  File "/usr/local/bin/pipx", line 3, in <module>
    import re
  File "/root/miniconda3/lib/python3.12/re/__init__.py", line 125, in <module>
    from . import _compiler, _parser
  File "/root/miniconda3/lib/python3.12/re/_compiler.py", line 18, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch
Removed /etc/systemd/system/multi-user.target.wants/gpustack.service.
GPUStack has been uninstalled.

**Comment by gitlawr** [comment]
It's using py3.12 while it's py3.11 at the begining of the issue. Is pipx messing up the Python environment?

**Comment by xlshao2021** [comment]
You might be right, I tried so many combination of setup so I forgot that I tried conda eariler.

Anyway, I uninstall it from conda and re-install it again. Please refer to the file
[gpustack20241030.log](https://github.com/user-attachments/files/17566146/gpustack20241030.log)
. I am still unable to access from a web browser even though it tells me GPUStack UI is available at http://localhost:443.

**Comment by gitlawr** [comment]
Could you show full logs from `/var/log/gpustack.log`?

**Comment by xlshao2021** [comment]
Sure 
[gpustack.log](https://github.com/user-attachments/files/17566748/gpustack.log)

**Comment by gitlawr** [comment]
Now the error looks identical to the one in https://github.com/gpustack/gpustack/issues/493#issuecomment-2443639623.

We don't find a way to reproduce, but have submitted a related fix.

It would be appreciate if you can try the wheel package built from the main branch: [linux-dist.zip](https://github.com/user-attachments/files/17570963/linux-dist.zip) (You can download from [github CI](https://github.com/gpustack/gpustack/actions/runs/11590902263) as well)

Example:
```
unzip linux-dist.zip
curl -sfL https://get.gpustack.ai | INSTALL_PACKAGE_SPEC=./gpustack-0.0.0-py3-none-manylinux2014_x86_64.whl sh -s - --port 80 --bootstrap-password 123456
```

If that works, we can have a patch release to address this issue.

**Comment by xlshao2021** [comment]
Yes, this version works. I am able to login via a browser now.

However, there's a problem when I tried to add a worker via Register Worker, the service was destroyed and I was no longer able to access via a web browser. I know this might be a quick hack, just keep it in mind.

Thx.

**Comment by gitlawr** [comment]
> add a worker via Register Worker, the service was destroyed
Do you have server logs for that?

**Comment by xlshao2021** [comment]
Seems each time the results are different ;-)  It is accessible via web browser this time but "Something went wrong". Please see the output messages and screenshots
<img width="1346" alt="Screenshot 2024-10-30 at 23 39 02" src="https://github.com/user-attachments/assets/1e3c182e-e1df-4e03-8031-0ba417529c6e">
<img width="1270" alt="Screenshot 2024-10-30 at 23 38 54" src="https://github.com/user-attachments/assets/676b11a2-d471-4b88-add5-d05bde427d99">
:

/var/log/gpustack.log:
2024-10-30T23:34:59+08:00 - gpustack.worker.tools_manager - INFO - downloading llama-box-linux-amd64-cuda-12.4 'v0.0.71'


terminal output:

$ cat /var/lib/gpustack/token
2bfe00133238d82f7171cc9049ea6e29



$ curl -sfL https://get.gpustack.ai | sh -s - --server-url http://x.x.x.x:4000 --token 2bfe00133238d82f7171cc9049ea6e29
[INFO]  GPUStack is already installed. Upgrading...
pipx >(setup:1110): pipx version is 1.7.1
pipx >(setup:1111): Default python interpreter is '/usr/bin/python3.11'
pipx >(package_name_from_spec:378): Determined package name: gpustack
pipx >(package_name_from_spec:379): Package name determined in 0.0s
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(needs_upgrade:99): Time since last upgrade of shared libs, in seconds: 170482. Upgrade will be run by pipx if greater than 2592000.
pipx >(run_subprocess:175): running <checking pip's availability>
Installing to existing venv 'gpustack'
pipx >(create_venv:164): Creating virtual environment
creating virtual environment...
pipx >(run_subprocess:175): running /usr/bin/python3.11 -m venv --without-pip /root/.local/share/pipx/venvs/gpustack
pipx >(run_subprocess:175): running <checking pip's availability>
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /root/.local/share/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python --version
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: gpustack[vllm]
pipx >(install_package:247): Installing gpustack from spec 'gpustack[vllm]'
installing gpustack from spec 'gpustack[vllm]'...
pipx >(run_subprocess:175): running /root/.local/share/pipx/venvs/gpustack/bin/python -m pip --no-input install --force-reinstall gpustack[vllm]

pipx >(run_subprocess:175): running <fetch_info_in_venv commands>
pipx >(get_venv_metadata_for_package:351): get_venv_metadata_for_package: 3367ms
pipx >(_parsed_package_to_package_or_url:139): cleaned package spec: gpustack[vllm]
pipx >(_symlink_package_resource:132): Force is true. Removing /root/.local/bin/gpustack.
  installed package gpustack 0.3.1, installed using Python 3.11.2
  These apps are now globally available
    - gpustack
done! ✨ 🌟 ✨
Removed /etc/systemd/system/multi-user.target.wants/gpustack.service.
[INFO]  Setting up GPUStack as a service using systemd.
Created symlink /etc/systemd/system/multi-user.target.wants/gpustack.service → /etc/systemd/system/gpustack.service.
[INFO]  Upgrade complete. 


# systemctl status gpustack
● gpustack.service - GPUStack Service
   Loaded: loaded (/etc/systemd/system/gpustack.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2024-10-30 23:34:53 CST; 2min 21s ago
 Main PID: 148491 (pt_main_thread)
    Tasks: 4 (limit: 97236)
   Memory: 740.7M
   CGroup: /system.slice/gpustack.service
           └─148491 /root/.local/share/pipx/venvs/gpustack/bin/python /root/.local/bin/gpusta>

Oct 30 23:34:53 iZ2ze4ge7l8kjzp1n3tkr2Z systemd[1]: Started GPUStack Service.

**Comment by gitlawr** [comment]
Are you adding the worker on the same node as server? It's meant to be a different node and is optional. By default GPUStack server embeds a worker so you can get started with it first. If you install as a worker on the server node it will destruct the setup.

**Comment by xlshao2021** [comment]
I see. I was installing them on a same machine. Thx!

**Comment by gitlawr** [comment]
This should be resolved in the latest release. Feel free to reopen the issue if you have further questions.
