### ISSUE TITLE
--tensor-split parameter for manual multi-GPU inference is not working

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#494]
**Describe the bug**

--tensor-split parameter for manual multi-GPU inference is not working.

**Steps to reproduce**

Deploy a GGUF model and add the backend parameter --tensor-split=1,1.

**Result**

The model is still running on only one GPU.

**Environment**

- GPUStack version: 0.3.1
- OS: Ubuntu 20.04
- GPU: RTX 4080

**Comment by Finenyaco** [comment]
Verified on main 27fa7fe

Note: Manual specification of parameters for distributed inference across workers is not supported.
