### ISSUE TITLE
Move "backend" out of advanced configuration

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#497]
Version: 0.3.1

Symptom: 
Currently, the inference backend configuration (vLLM or llama-box) is hidden in advanced configuration and is not visible to users by default. For most of the model formats other than gguf in huggingface, we will choose vLLM as backend as default. If the user uses a Mac and chooses a non-GAF model, the deployment will be stuck in pending status without helpful information. 

Suggestion:
Basic config should be the primary and mandatory configurations required for successful deployment. Currently inference backend should be a basic config exposed to users, as it will not work if incorrect backend and model formats are chosen based on the hardware.

**Comment by Finenyaco** [comment]
Verified in UI version 4391705
