### ISSUE TITLE
Support --cache-dir parameter to configure model cache independently

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#504]
Currently we can configure --data-dir to let GPUStack store config data and model cache to different path other than /var/lib/gpustack. It will be better to add a --cache-dir parameter to set model cache independently. Thus users can use a NFS path and mount it to all nodes or containers and share model files between them. We can't share --data-dir between workers as it contains per-worker information.

**Comment by Finenyaco** [comment]
Verified on main 631b8db
