### ISSUE TITLE
Model instance serving ip not updated in database correctly after worker restart and ip change

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#510]
Version: 0.3.1
Step to reproduce:
1. Deploy a model in GPUStack.
2. Change worker ip and restart worker.
3. Try to access model in playground. Failed with service unavailable.
4. Try to curl the serving server with new ip directly will get proper response.
5. The serving ip of model instance in database was not updated correctly.
6. Recreate model instance will get it updated.

**Comment by Finenyaco** [comment]
Verified on main acd998c
