### ISSUE TITLE
Support offline running in docker

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#525]
We need to provide a complete docker image to enable GPUStack to run in offline environments, removing dependencies on internet access.
For example: remove checks for tool download URLs.

**Comment by gitlawr** [comment]
How does this differ from https://github.com/gpustack/gpustack/issues/408?

**Comment by linyinli** [comment]
#408 addresses offline installation, but there may still be other internet dependencies when using GPUStack. I would like the test cases to cover using of GPUStack in an offline environment—not just installation and initial startup, so tracking in this issue.

**Comment by Finenyaco** [comment]
Verified on main 7082340
