### ISSUE TITLE
Predict GPU memory get wrong answer when context length is not 8192

### ISSUE THREAD

**Issue by Readon** [gpustack/gpustack#532]
**Describe the bug**

**Steps to reproduce**

1. Go to 'Deploy model'
2. deploy a model with context length 32768 by "--ctx-size=32768" for backend parameter.
3. the memory usage for scheduler is for 8192 only, but not 32768.

**Result**

Model runs failed

**Expected behavior**

the gpuparser parameter of ctx-size should be modified by backend parameter if it is existed.
The code related could be [here](https://github.com/gpustack/gpustack/blob/15d5c8736ba1c27844aef0e2ccd9b9209622847c/gpustack/scheduler/calculator.py#L90).

**Environment**

- GPUStack version:
- OS: Ubuntu 22.04
- GPU: 

**Additional context**

**Comment by Finenyaco** [comment]
Verified on main 27fa7fe
