### ISSUE TITLE
Often requires multiple attempts to successfully load the model repository

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#543]
**Describe the bug**

In environments with poor network conditions, when deploying the model, it often requires multiple attempts to successfully load the model repository.

User feedback:
<img width="781" alt="image" src="https://github.com/user-attachments/assets/fcfcb346-e84a-4ed5-bd66-c3451da801ac">

<img width="756" alt="image" src="https://github.com/user-attachments/assets/66fedcc9-2fc2-4729-9d4c-bf843ee71583">

**Comment by Finenyaco** [comment]
Verified on main 27fa7fe13b75426cdc2be1e58d6a275803e1d290
