### ISSUE TITLE
Multicore CPU utilization 

### ISSUE THREAD

**Issue by ivlovric** [gpustack/gpustack#569]
Hi,

I am experimenting with gpustack and I noticed when hosting LLMs on CPU only with llama.cpp as backend that only one CPU core is being utilised when inquering such LLM. 
Can multicore processing be added as well? Maybe as additional option alongside with backend?

Also linking available option for this from llama.cpp repo > https://github.com/ggerganov/llama.cpp/discussions/391

EDIT: gpustack might be using multicore after all and my observation could be mistaken. If so, maybe to see does it make sense to specify number of cores to use

thanks

**Comment by thxCode** [comment]
customize the llama-box(llama.cpp) with `--threads`. by default, it will choose the thread number according to the OS environment.

<img width="858" alt="image" src="https://github.com/user-attachments/assets/35995867-7152-4671-b257-abdcbc486f3e">
