### ISSUE TITLE
Optimize path check in installation script

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#574]
Currently, we will use ${which_gpustack} output as GPUStack command path in Linux or macOS. Sometimes "which gpustack" doesn't return the path to gpustack command, it will cause GPUStack service failed to start due to an incorrect service command path.  It may be related to pipx path problem or some other issue that we couldn't easily reproduce. 

For some of them, manually rerun pipx ensurepath is a workaround. We should optimize the installation script and do exception handling in which gpustack check. If the return is empty, we should break the installation and give some hints. The hints should prompt users to manually run pipx ensurepath and re-run the installation script.

**Comment by Finenyaco** [comment]
Verified in main
