### ISSUE TITLE
Installation failed(failed to build shellcheck_py)

### ISSUE THREAD

**Issue by sayhi-afk** [gpustack/gpustack#589]
I was asked to build wheel for shellcheck_py while installing gpustack. However, the latest version only supported on x_86 system which is different from my aarch64 system.
I found an old version and successfully set it up, but still cannot skip shellcheck_py while installing gpustack.
How to fix it?
<img width="947" alt="c046c17b00284fbcae8534ae681f5cc" src="https://github.com/user-attachments/assets/29b7e490-624a-4431-b912-f00b10c1959a">
<img width="947" alt="c9f61b2fceae81cee5766977214e48e" src="https://github.com/user-attachments/assets/3c93a689-96ad-48ce-8567-5aacaced4428">

**Comment by gitlawr** [comment]
> error: <urlopen error [Errno 110] Connection timed out>

From this line we can tell it fails to build the package due to networking issue. In you environment, try:
```
pip install shellcheck-py --index-url https://pypi.tuna.tsinghua.edu.cn/simple
```

More context:
1. shellcheck-py does not provide linux-aarch64 wheel package in pypi but it can build from source on installation.
2. GPUStack might don't need this dependency in runtime, we will investigate if it should be removed as dev dependency.

**Comment by sayhi-afk** [comment]
Thanks for your reply. Actually we have already tried your methods before :
1.We have tried "pip install shellcheck-py --index-url https://pypi.tuna.tsinghua.edu.cn/simple"   and it failed
2.We have tried building shellcheck_py from source on installation successfully.  But still cannot skip shellcheck_py while installing GPUstack which is so weird.

I don't know if there's another solution. Hoping you can investigate if it should be removed as dev dependency.

**Comment by linyinli** [comment]
@sayhi-afk Try to upgrade some packages and retry again.
```
pip install --upgrade pip setuptools wheel
```

**Comment by Finenyaco** [comment]
Verified on main c9bb9f3. shellcheck-py  has been removed.

<img width="571" alt="image" src="https://github.com/user-attachments/assets/502485ac-7a0e-4ed4-b35a-0d0b69a98af0">
