### ISSUE TITLE
Normalize the relevance_score returned by the rerank API

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#593]
**Is your enhancement related to a problem? Please describe.**
It seems that normalizing the relevance_score returned by the rerank API is a recommended practice:

Finally, if I have to choose the best predictor among these three, I would give it to the reranker model.
For two reasons:
The reranker model's trendline on both impressions and clicks is more well-spanned over the X-axis compared to the embedding model's trendline, giving it more "dynamic range," which makes it closer to the ground truth trendline.
The score is well-distributed between 0 and 1. Note that this is mostly because our latest Reranker v2 model is calibrated, whereas our earlier [jina-embeddings-v2-base-en](https://jina.ai/?sui&model=jina-embeddings-v2-base-en) released in Oct. 2023 was not, so you can see its values spread over 0.60 to 0.90. That said, this second reason has nothing to do with its approximation to G(q,d)G(q,d); **it is just that a well-calibrated semantic score between 0 and 1 is more intuitive to understand and compare.**

https://huggingface.co/BAAI/bge-reranker-v2-m3
**You can get a relevance score by inputting query and passage to the reranker. And the score can be mapped to a float value in [0,1] by sigmoid function.**
```
from FlagEmbedding import FlagReranker
reranker = FlagReranker('BAAI/bge-reranker-v2-m3', use_fp16=True) # Setting use_fp16 to True speeds up computation with a slight performance degradation

score = reranker.compute_score(['query', 'passage'])
print(score) # -5.65234375

# You can map the scores into 0-1 by set "normalize=True", which will apply sigmoid function to the score
score = reranker.compute_score(['query', 'passage'], normalize=True)
print(score) # 0.003497010252573502
```

**Describe the solution you'd like**
Normalize the relevance_score returned by the rerank API, enabled by default and allowed to be disabled.

**Comment by thxCode** [comment]
https://github.com/gpustack/llama-box/releases/tag/v0.0.80

**Comment by thxCode** [comment]
closed as completed
