### ISSUE TITLE
Add \n in init_admin_password and token 

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#594]
Currently we don't add  '\n' in the output of init_admin_password and token file, which will cause some issues as:

1. In Mac, there is an additional '%' in the output if the user uses cat xxx directly, which may cause users input incorrect password or token.
2. In Linux, the output will be in the same line with the shell prefix. Sometimes there is a @ in the password which may not easy for the users to identify the correct password. 

Add '\n' can resolve the problem.

**Comment by Finenyaco** [comment]
Verified on main d7d0344
