### ISSUE TITLE
Failed to chat in the playground

### ISSUE THREAD

**Issue by Finenyaco** [gpustack/gpustack#609]
**Describe the bug**

**Steps to reproduce**

1. Deploy a model.
2. Go to playground and chat.

**Result**

1. Returned an error:  Service unavailable. Please retry your requests after a brief wait.
<img width="2332" alt="image" src="https://github.com/user-attachments/assets/6a1a456d-9b80-4388-9e9e-68c268534d6a">

2. Failed to curl after setting 'stream=true'
<img width="2558" alt="image" src="https://github.com/user-attachments/assets/74f1b381-6e98-4561-8705-ed98e80e4b75">

**Expected behavior**

**Environment**

- GPUStack version: main c9bb9f3
- OS: Ubuntu 22.04
- GPU: NVIDIA 4090

**Additional context**

**Comment by gitlawr** [comment]
Should be resolved with box 0.0.81

**Comment by Finenyaco** [comment]
**GPUStack version:** a14d498
**llama-box:** v0.0.81

**Test Result:** Pass

<img width="2318" alt="image" src="https://github.com/user-attachments/assets/b4cd66f8-a950-4318-80fd-070e419bff76">
