### ISSUE TITLE
API Endpoint usage for other front-ends

### ISSUE THREAD

**Issue by Lex-au** [gpustack/gpustack#614]
Hi Team,

Does API Endpoint usage extend to other front-ends, like open-webui? Currently their front-end is the best with inbuilt langchain functionality and chat storage.

I have tried and setup API, yet models to not load from the endpoint usage. I infer this is due to incompatibility or perhaps I've done something incorrect.

**Comment by gitlawr** [comment]
The API is OpenAI-compatible so it works for any front-end built for it, including open-webui. Be aware that GPUStack serves at `/v1-openai`(https://docs.gpustack.ai/0.3/user-guide/openai-compatible-apis/)

**Comment by Lex-au** [comment]
> #129 There are setup commands for Open WebUI in the above issue. I am not sure if it's still valid, but you can check it as a reference.

Cheers for the documentation. Endpoints are working now. Fantastic.

**Comment by Lex-au** [comment]
FYI: No need to serve enviroments. Ensure your endpoint is directed correctly http://ip/v1-openai and it will serve.
