### ISSUE TITLE
After docker install there is no tokenfile in /var/lib/gpustack

### ISSUE THREAD

**Issue by ivlovric** [gpustack/gpustack#615]
Cant find /var/lib/gpustack/token file on server node to connect worker as per https://github.com/gpustack/gpustack/blob/fbb5359f2c459cf34169d3f47b401aaf450a029c/docs/tutorials/setting-up-a-multi-node-gpustack-cluster.md?plain=1#L41

**Steps to reproduce**

1. docker run -d  -p 80:80 -p 10151:10151 --ipc=host -v gpustack-data2:/var/lib/gpustack gpustack/gpustack:main-cpu -t gpustack-cpu
2. Connect to container "docker exec -it 6 bash"
3. Check for token "cat /var/lib/gpustack/token" - there is no such file
4. Content of /var/lib/gpustack/ is this: 
cache  database.db  initial_admin_password  jwt_secret_key  log  worker_name

**Result**

No token file

**Expected behavior**

token file should be generated and used to connect worker node

**Environment**

- GPUStack version: gpustack/gpustack:main-cpu, tried also with container gpustack/gpustack with same result
- OS: Linux Rocky
- GPU: CPU only

**Comment by gitlawr** [comment]
Do you see any error in container logs?

**Comment by pengjiang80** [comment]
I can reproduce with the main-cpu image. The main-cpu image is still in development and it should be a bug. We will do more investigation. Thanks for reporting this.

**Comment by pengjiang80** [comment]
For the time being, you can try the standard installation without docker. It will generate a token successfully. We use pipx venv for gpustack installation so it will not mess up your environment. And you can uninstall it by running the /var/lib/gpustack/unisntall.sh script.

**Comment by pengjiang80** [comment]
Sorry. Made a mistake. You used 
docker run -d -p 80:80 -p 10151:10151 --ipc=host -v gpustack-data2:/var/lib/gpustack gpustack/gpustack:main-cpu -t gpustack-cpu

-t is the parameter that will be passed to the GPUStack startup command, which is the token. So gpustack-cpu will be the token, and the random token will not be generated. I didn't notice this and assumed it was a -n.

**Comment by ivlovric** [comment]
Thank you, I overlooked -t as well as I was using it previously to build and tag image myself.
Closing this now
