### ISSUE TITLE
The generated images may get truncated

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#644]
**Describe the bug**

![image](https://github.com/user-attachments/assets/11042a8b-1e36-4f95-92ad-1a2738c6ad96)

**Steps to reproduce**

Generate more than two images with high quality and attempt multiple times.

**Environment**

- GPUStack version: 0.4.0 rc
- OS: macOS 14.4
- GPU: M2 Ultra

**Comment by Finenyaco** [comment]
Verified on main 30b4651, UI version bd418b2
