### ISSUE TITLE
downloading llama-box-linux-amd64-cuda-12.4 everytime for restart docker image

### ISSUE THREAD

**Issue by verigle** [gpustack/gpustack#654]
**Is your enhancement related to a problem? Please describe.**

I'm frequently inconvenienced by the need to download tools like `llama-box` and `gguf-parse` each time I use the GPUStack Docker image, which is time-consuming and inefficient.

**Describe the solution you'd like**

I would like the GPUStack Docker image to include tools such as `llama-box` and `gguf-parse` by default, eliminating the need to download them separately each time the image is used. This would streamline the process and make it more efficient.

**Describe alternatives you've considered**

I have considered manually installing these tools within my workflow, but this adds extra steps and potential for errors. Another alternative is to use a different Docker image that already includes these tools, but this would require finding a suitable image and ensuring it meets all other requirements for my projects.

**Additional context**

The inclusion of `llama-box` and `gguf-parse` in the GPUStack Docker image would be particularly beneficial for users who frequently work with GGUF formatted models, as these tools are essential for model conversion and quantization. This enhancement would not only save time but also ensure consistency and reliability across different projects and environments.

**Comment by gitlawr** [comment]
Thank you for your feedback. This is addressed in https://github.com/gpustack/gpustack/issues/525 and will be available in v0.4.0.

**Comment by gitlawr** [comment]
Should be resolved as v0.4.0 is out. Feel free to reopen if you have further questions
