### ISSUE TITLE
Incorrect Form Padding

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#660]
**Steps to reproduce**

1. Click `Models` page
2. Click Chat playground

**Result**

<img width="380" alt="image" src="https://github.com/user-attachments/assets/e382da71-f1ff-4f16-8b6e-f50f0660c67a">

After a refresh:
<img width="438" alt="image" src="https://github.com/user-attachments/assets/87dd715f-fc1e-45dd-b60c-46b47650799a">
**Environment**

- GPUStack version: main

**Comment by Finenyaco** [comment]
Verified on UI 4351618
