### ISSUE TITLE
Voices are not available when model is initializing

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#663]
**Describe the bug**

<img width="1738" alt="image" src="https://github.com/user-attachments/assets/56f1c935-b88a-4383-9711-c4291443f937">
**Steps to reproduce**

1. Deploy CosyVoice
2. Go to the audio playground

**Result**

Voice dropdown is empty but there's no any info in the UI

**Expected behavior**

Maybe tell users: 
```
Voices are unavailable. The model may still be initializing. Please refresh after a brief wait.
```

**Environment**

- GPUStack version: main

**Comment by Finenyaco** [comment]
Verified on UI e622636

![Image](https://github.com/user-attachments/assets/586f32c7-4006-4126-ba79-04596b5ad557)
