### ISSUE TITLE
Support model upgrades

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#681]
Support model upgrades, such as upgrading Qwen 2 to Qwen 2.5, without changing the model name used in the AI applications.

A simple way to support this is by allowing the editing of the Repo ID, File Name, Ollama Model and Model Path when editing the model.

The UX for editing models also needs to be adjusted.

**Comment by pengjiang80** [comment]
It's also helpful for users to choose/change different quantization levels after deployment.

**Comment by Finenyaco** [comment]
Verified in UI version cb5d9f6
