### ISSUE TITLE
Add clear instruction for Mac and Windows users to click the GGUF option when deploying from Huggingface or Modelscope

### ISSUE THREAD

**Issue by pengjiang80** [gpustack/gpustack#687]
Version: 0.3.2
Symptom:
1. The GGUF option is not enabled by default, and most models in Huggingface or Modelscope are not in GGUF format.
2. Mac or Windows users may choose incompatible model formats and can't deploy the model successfully.
3. We have added more information in the pending status message in 0.4. But it's not quite straightforward for users.

Enhancement:
Add a text hint in the model deployment page and clearly state the GGUF format requirements for Mac and Windows users.

**Comment by Finenyaco** [comment]
Verified in UI version 9f40e2c
