### ISSUE TITLE
CPU Offloading is not enabled but the model is still entirely offloaded to the CPU

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#694]
**Describe the bug**

CPU Offloading is not enabled but the model is still entirely offloaded to the CPU.

**Steps to reproduce**

Deploy a GGUF model via local path, ensuring that this model exceeds the resource requirements.

**Result**
<img width="596" alt="image" src="https://github.com/user-attachments/assets/d8a2fa33-f4c0-4e04-b741-fbb529237060">

<img width="757" alt="image" src="https://github.com/user-attachments/assets/ab585662-3fb4-4e37-97bc-9f7a371ad105">

**Environment**

- GPUStack version: 28e5269
- OS: macOS 15.1
- GPU: M1 Pro

**Comment by gitlawr** [comment]
Happens when the local model is not available on server.

**Comment by Finenyaco** [comment]
Verified on main 81ac226

<img width="770" alt="image" src="https://github.com/user-attachments/assets/a16b5c1c-4902-446c-9e83-c343cddda27b">
