### ISSUE TITLE
Failed to calculate model resource claim for multipart model downloads

### ISSUE THREAD

**Issue by Steel-skull** [gpustack/gpustack#702]
**Describe the bug**

When going to download a multi file GGUF quant from Bartowski im getting this error

```
Failed to calculate model resource claim: Failed to get the file for model lazarus-2407-100b, error: File Lazarus-2407-100B-IQ4_XS/Lazarus-2407-100B-IQ4_XS*.gguf not found in bartowski/Lazarus-2407-100B-GGUF
```

This works for models in other repos that doesn't use the structure that Bartowski is using example:

This repo works:

```
TheDrummer/Endurance-100B-v1-GGUF
```

**Steps to reproduce**

1. Go to models
2. Deploy model then Hugging face
3. Search bartowski/Lazarus-2407-100B-GGUF
4. Select any model larger than one part
5. Deploy
6. Find error in Models

**Result**

```
Failed to calculate model resource claim: Failed to get the file for model lazarus-2407-100b, error: File Lazarus-2407-100B-IQ4_XS/Lazarus-2407-100B-IQ4_XS*.gguf not found in bartowski/Lazarus-2407-100B-GGUF
```

**Expected behavior**

Download and parse model

**Environment**

- GPUStack version: latest
- OS: linux
- GPU: 3090 x 3

**Comment by Finenyaco** [comment]
Verified on  main 1d54441

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/e3922892-0022-454e-ae32-34cc4a08aa88">
