### ISSUE TITLE
Clean up backend parameters options for vox-box

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#704]
**Is your enhancement related to a problem? Please describe.**

Avoid showing llama-box/vLLM parameters for vox-box.

<img width="1280" alt="image" src="https://github.com/user-attachments/assets/c076f9c1-a5a4-4967-b0ec-3de5a7ce36b6">
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/cc7a9d0c-b863-4a98-bb2a-ad288ee14538">

**Comment by Finenyaco** [comment]
Verified in UI version bed3684
