### ISSUE TITLE
Retry error on draw

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#720]
**Steps to reproduce**

1. Following the draw command in https://github.com/gpustack/gpustack/blob/main/docs/quickstart.md#getting-started

**Result**

1. Get the error printed in console: 

RetryError[<Future at 0x114db7010 state=finished raised APIRequestError>]

2. Both `[stable-diffusion-v3-5-large-turbo-Q4_0.gguf](https://huggingface.co/gpustack/stable-diffusion-v3-5-large-turbo-GGUF/blob/main/stable-diffusion-v3-5-large-turbo-Q4_0.gguf)` and [stable-diffusion-v3-5-large-turbo-pure-Q4_0.gguf](https://huggingface.co/gpustack/stable-diffusion-v3-5-large-turbo-GGUF/blob/main/stable-diffusion-v3-5-large-turbo-pure-Q4_0.gguf) are downloaded.

**Expected behavior**

Command succeeds and avoid downloading unused model files.

**Environment**

- GPUStack version: main

**Comment by Finenyaco** [comment]
Verified in main a0249f8
