### ISSUE TITLE
The speech-to-text functionality in Node.js code is not working as expected.

### ISSUE THREAD

**Issue by hibig** [gpustack/gpustack#732]
**Describe the bug**

**Steps to reproduce**

1. Go to  `Audio`, click `Speech to Text` tab.
2. Click `View Code`, and select `Nodejs` item.
3. Run code:
<img width="712" alt="Snipaste_2024-12-05_19-30-36" src="https://github.com/user-attachments/assets/39f998e9-e9d5-4b18-82dc-14bd8f21db4b">

**Result**
Response: 
`{
  status_code: 400,
  detail: 'Unsupported file format: application/octet-stream',
  headers: null
}`

**Expected behavior**

**Environment**

- GPUStack version:
- OS:
- GPU:

**Additional context**

**Comment by hibig** [comment]
It works if you use the Axios library for the request.

<img width="602" alt="Snipaste_2024-12-05_19-40-41" src="https://github.com/user-attachments/assets/341aaae6-d9f7-4868-ba37-6671186f7cb0">

**Comment by Finenyaco** [comment]
Verified in main 494b70c
