### ISSUE TITLE
Voice to Text Failed

### ISSUE THREAD

**Issue by linuxliker** [gpustack/gpustack#746]
**Describe the bug**
![image](https://github.com/user-attachments/assets/db4d7337-0503-44af-9e94-56e7a8958b28)
Failed to transcribe audio, [Errno 2] No such file or directory: 'ffmpeg'

Is docker image not install ffmpeg inside cause this error?

**Steps to reproduce**

**Result**

**Expected behavior**

**Environment**

- GPUStack version:
- OS:  Docker image   gpustack/gpustack:latest
- GPU:   Nvida L20

**Additional context**

**Comment by gitlawr** [comment]
Which model are you using?

**Comment by linuxliker** [comment]
> Which model are you using?

ModelScope/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online

**Comment by gitlawr** [comment]
<img width="1481" alt="image" src="https://github.com/user-attachments/assets/3eecdd4e-2d31-41a4-86af-336391a88e1f">

I was able to do inference with this model, and would like to get more details to reproduce.

1. What's the host OS/Arch?
2. Can you show output of `docker image inspect --format='{{.RepoDigests}}' gpustack/gpustack:latest` (We had a CI issue publishing the latest tag which is fixed, but want to check the image being used)
3. Can you provide the command running docker?
4. Did you see any error logs in `Models page UI -> expand model instances -> view logs action`?

**Comment by linuxliker** [comment]
1、uname -a 
Linux aliyun-l20 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

2、docker image inspect --format='{{.RepoDigests}}' xxxxx-registry.cn-hangzhou.cr.aliyuncs.com/gpustack/gpustack:latest
[xxxxxx-registry.cn-hangzhou.cr.aliyuncs.com/gpustack/gpustack@sha256:61edf96a82eaccdad7243cd60ae93ed786642833123099c0d79dfae1d13f408a]
I hide the key url path. My repo is mirror from dockerhub gpustack/gpustack:latest

3、docker command
 docker run -d --gpus all -p 9997:80   -e HF_ENDPOINT=https://hf-mirror.com  --ipc=host -v /root/huanqi/gpustack-data:/var/lib/gpustack xxxxxx-registry.cn-hangzhou.cr.aliyuncs.com/gpustack/gpustack

4、error logs in Models:
/usr/local/lib/python3.10/dist-packages/funasr/train_utils/load_pretrained_model.py:39: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ori_state = torch.load(path, map_location=map_location)
2024-12-10T12:50:14+00:00 - root - INFO - scope_map: ['module.', 'None']
2024-12-10T12:50:14+00:00 - root - INFO - excludes: None
2024-12-10T12:50:14+00:00 - root - INFO - Loading ckpt: /var/lib/gpustack/cache/model_scope/iic/speech_paraformer-large_asr_nat-zh-cn-16k-common-vocab8404-online/model.pt, status: <All keys matched successfully>
2024-12-10T12:50:14+00:00 - vox_box.server.server - INFO - Starting Speech Box server.
2024-12-10T12:50:14+00:00 - vox_box.server.server - INFO - Serving on 0.0.0.0:40530.
2024-12-10T12:50:30+00:00 - vox_box.utils.log - INFO - Starting transcribe method in FunASR
2024-12-10T12:50:30+00:00 - vox_box.backends.stt.funasr - WARNING - Param `timestamp_granularities` is not supported for FunASR
2024-12-10T12:50:30+00:00 - vox_box.backends.stt.funasr - INFO - Params `prompt` and `temperature` are only supported for FunASR llm asr model, will ignore them if model isn't supported
Notice: ffmpeg is not installed. torchaudio is used to load audio
If you want to use ffmpeg backend to load audio, please install it by:
	sudo apt install ffmpeg # ubuntu
	# brew install ffmpeg # mac
Key Conformer already exists in model_classes, re-register
Key Linear already exists in adaptor_classes, re-register
Key TransformerDecoder already exists in decoder_classes, re-register
Key LightweightConvolutionTransformerDecoder already exists in decoder_classes, re-register
Key LightweightConvolution2DTransformerDecoder already exists in decoder_classes, re-register
Key DynamicConvolutionTransformerDecoder already exists in decoder_classes, re-register
Key DynamicConvolution2DTransformerDecoder already exists in decoder_classes, re-register
funasr version: 1.1.14.
  0%|          | 0/1 [00:00<?, ?it/s]

**Comment by aiwantaozi** [comment]
We have identified that uploading audio data through recording may cause this issue. Thank you for bringing this to our attention; we will work to resolve it as quickly as possible. In the meantime, you may consider directly uploading audio files as an alternative.

**Comment by Finenyaco** [comment]
Verified in main 5a6e944
