### ISSUE TITLE
Unable to use the LLaVA model deployed by llama-box

### ISSUE THREAD

**Issue by linyinli** [gpustack/gpustack#749]
**Describe the bug**

Unable to use the LLaVA model deployed by llama-box.

**Steps to reproduce**

1. Download the `xtuner/llava-phi-3-mini-gguf` model from Hugging Face.
2. Deploy the llava-phi-3-mini-f16.gguf model from Local Path.
3. Add the backend parameter: `--mmproj=/Users/user/llava-phi-3-mini-gguf/llava-phi-3-mini-mmproj-f16.gguf`
4. Test it on the Playground.

**Result**
Model crashed:
<img width="1776" alt="image" src="https://github.com/user-attachments/assets/52d965c2-625f-466c-873b-cedf404a4dce">

**Environment**

- GPUStack version: v0.4.0
- OS: macOS 15.1
- GPU: M1 Pro

**Comment by gitlawr** [comment]
Fixed in llama-box v0.0.90. In GPUStack v0.4.0 you can specify the backend version as a workaround for llava.

**Comment by linyinli** [comment]
Verified.

**Comment by Finenyaco** [comment]
Verified in main 450b18a, llama-box version v0.0.91
