### ISSUE TITLE
Fail to deploy ollama models

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#759]
**Steps to reproduce**

1. Install GPUStack
2. Deploy qwen2.5:0.5b using ollama source.

**Result**

The model instance is in error status with the following message:

```
Failed to calculate model resource claim: ("Failed to execution [PosixPath('/usr/local/lib/python3.10/dist-packages/gpustack/third_party/bin/gguf-parser/gguf-parser'), '--in-max-ctx-size', '--skip-tokenizer', '--skip-architecture', '--skip-metadata', '--image-vae-tiling', '--cache-expiration', '168h0m0s', '--no-mmap', '--json', '--ctx-size', '8192', '--cache-path', '/var/lib/gpustack/cache/gguf-parser', '--gpu-layers', '-1', '-ol-model', 'qwen2.5:0.5b', '-ol-base-url', 'https://registry.ollama.ai'], error: Command '[PosixPath('/usr/local/lib/python3.10/dist-packages/gpustack/third_party/bin/gguf-parser/gguf-parser'), '--in-max-ctx-size', '--skip-tokenizer', '--skip-architecture', '--skip-metadata', '--image-vae-tiling', '--cache-expiration', '168h0m0s', '--no-mmap', '--json', '--ctx-size', '8192', '--cache-path', '/var/lib/gpustack/cache/gguf-parser', '--gpu-layers', '-1', '-ol-model', 'qwen2.5:0.5b', '-ol-base-url', 'https://registry.ollama.ai']' returned non-zero exit status 1., ", 'stderr: failed to parse GGUF file: open http file: stat: do head request: stat: not support range download\n, ', 'stdout: ')
```

**Environment**

- GPUStack version: v0.4.0

**Comment by Finenyaco** [comment]
Verified in main 5a6e944

**Comment by dduck999** [comment]
This is happening to https://www.ollama.com/library/llama3.2-vision model too. 


Failed to calculate model resource claim: ("Failed to execution [PosixPath('/usr/local/lib/python3.10/dist-packages/gpustack/third_party/bin/gguf-parser/gguf-parser'), '--in-max-ctx-size', '--skip-tokenizer', '--skip-architecture', '--skip-metadata', '--image-vae-tiling', '--cache-expiration', '168h0m0s', '--platform-footprint', '150,500', '--no-mmap', '--json', '--ctx-size', '8192', '--cache-path', '/var/lib/gpustack/cache/gguf-parser', '--gpu-layers', '-1', '-ol-model', 'llama3.2-vision', '-ol-base-url', 'https://registry.ollama.ai'], error: Command '[PosixPath('/usr/local/lib/python3.10/dist-packages/gpustack/third_party/bin/gguf-parser/gguf-parser'), '--in-max-ctx-size', '--skip-tokenizer', '--skip-architecture', '--skip-metadata', '--image-vae-tiling', '--cache-expiration', '168h0m0s', '--platform-footprint', '150,500', '--no-mmap', '--json', '--ctx-size', '8192', '--cache-path', '/var/lib/gpustack/cache/gguf-parser', '--gpu-layers', '-1', '-ol-model', 'llama3.2-vision', '-ol-base-url', 'https://registry.ollama.ai']' returned non-zero exit status 1., ", 'stderr: failed to parse GGUF file: complete ollama model: do request https://registry.ollama.ai/v2/library/llama3.2-vision/manifests/latest: status code 412\n, ', 'stdout: ')

**Comment by gitlawr** [comment]
@dduck999 Since it's different from the original issue I'm moving it to https://github.com/gpustack/gpustack/issues/1398 for further discussion. Please see the context there.
