### ISSUE TITLE
Improve UX for searching models

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#77]
**Is your enhancement related to a problem? Please describe.**

When deploying a model, searching from huggingface may not be straightforward.

**Describe the solution you'd like**

1. Show commonly used models.
2. Provide more info such as arch, parameters, quantization, popularity, etc.

**Comment by sheng-liang** [comment]
I agree this will be a great feature to have!

**Comment by Finenyaco** [comment]
Verified in main (02903db), UI version 8bb1961.
