### ISSUE TITLE
Add stop/start action for models

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#796]
**Is your enhancement related to a problem? Please describe.**

Simplify common scaling cases.

**Describe the solution you'd like**

stop: Alias of scaling to 0.
start: Alias os scaling from 0 to 1.

**Comment by Finenyaco** [comment]
Verified in UI version 4391705

**Comment by gitlawr** [comment]
Should we add confirmation on stop?

**Comment by Finenyaco** [comment]
It would be better to add a confirmation window to prevent inadvertent operations without being aware of it.

**Comment by Finenyaco** [comment]
UI version: e74cda3

Two `succeed!` messages displayed after stopping.
<img width="682" alt="image" src="https://github.com/user-attachments/assets/35e3cae9-c334-4ea9-9ba1-05c00068b231" />

**Comment by Finenyaco** [comment]
Verified in UI version: 972ee69
