### ISSUE TITLE
请问模型部署时的“副本数”是什么意思？

### ISSUE THREAD

**Issue by czhcc** [gpustack/gpustack#800]
我想同一个模型，部署到一台机的两张卡上，但使用同一个模型名称。起到一个分发的作用。
这个“副本数”可以解决吗？如果不行，有什么办法吗？

---

I want to deploy the same model onto two GPUs on a single machine, using the same model name, to act as a form of load distribution. Can the ‘replicas’ solve this? If not, what other solutions are there?

**Comment by gitlawr** [comment]
Yes, the replicas is dedicated for this case. You can set replicas to 2, and inference requrests are distributed to two model instances with the same model name. By default, GPUStack use `spread` [placement strategy](https://docs.gpustack.ai/latest/user-guide/model-management/#auto) so it should run each on a different card when capable. If you have multiple nodes, you can use worker selector to decide which nodes to schedule.

**Comment by czhcc** [comment]
好的，多谢
