### ISSUE TITLE
Bypass initialisation/download check?

### ISSUE THREAD

**Issue by Lex-au** [gpustack/gpustack#806]
Hi Team,

Is there a parramater or command we can append to prevent the initialisation check? Specifically, bypassing the "download" check. I've noticed a lot of the time it checks to confirm the file is downloaded before loading.

Scheduled > Initialisation > Download > Running

**Comment by gitlawr** [comment]
There's no option to skip this phase right now. Is it causing trouble?

**Comment by Lex-au** [comment]
For use cases like intranets yeah it's problematic. Could this possible become an enhancement for future releases?

**Comment by gitlawr** [comment]
For Intranets now we have https://docs.gpustack.ai/latest/user-guide/model-management/#deploying-a-local-path-model, does that help?

**Comment by Lex-au** [comment]
> For Intranets now we have https://docs.gpustack.ai/latest/user-guide/model-management/#deploying-a-local-path-model, does that help?

Perfect! ty so much.
