### ISSUE TITLE
Windos10进行部署模型时日志未显示，模型下载成功后显示Runing之后变成Error（Inference server exited with code 0）

### ISSUE THREAD

**Issue by bugrootof** [gpustack/gpustack#808]
1. 在模型->部署模型选择魔塔社区后点击保存模型成功下载
![image](https://github.com/user-attachments/assets/92c60148-5086-4bc1-a8c8-9abb770a9138)
2.隔一段时间出现Error（Inference server exited with code 0.）
![image](https://github.com/user-attachments/assets/436ba6c0-619e-4c0a-b2ec-93d648919c4d)
3.点击日志查看不到任何输出的日志
![image](https://github.com/user-attachments/assets/f6caf434-1598-49e7-a979-d7ebcb1c7228)

- GPUStack version: v0.4.1
- OS: Windows 10 专业工作站版
- GPU: RTX3090

主要碰到两个问题：1.模型日志未显示 2.模型下载成功后使用模型出现Inference server exited with code 0

**Comment by gitlawr** [comment]
Can you check if installing dependencies in https://github.com/gpustack/llama-box/issues/10#issuecomment-2544733124 help resolve this?

**Comment by bugrootof** [comment]
> Can you check if installing dependencies in [gpustack/llama-box#10 (comment)](https://github.com/gpustack/llama-box/issues/10#issuecomment-2544733124) help resolve this?您能否检查在 [gpustack/llama-box#10 （评论）](https://github.com/gpustack/llama-box/issues/10#issuecomment-2544733124)中安装依赖项是否有助于解决此问题？

![image](https://github.com/user-attachments/assets/eaa8f531-b615-45e8-a11a-a3943937dd7c)

**Comment by gitlawr** [comment]
Can you provide output of `nvidia-smi` to check if CUDA is installed properly

**Comment by bugrootof** [comment]
![image](https://github.co@gitlawr /user-attachments/assets/69e457c9-4aaf-4988-83a6-c1361e447824)
@

**Comment by bugrootof** [comment]
![image](https://github.com/user-attachments/assets/9f5e99ee-7e4b-4461-aad5-38a530059667)
@gitlawr

**Comment by bugrootof** [comment]
![image](https://github.com/user-attachments/assets/3ac8d538-dce4-436a-a3b5-d5526755268d)

@gitlawr

**Comment by thxCode** [comment]
have you installed Nvidia sub-package `cublas`? https://github.com/gpustack/llama-box/blob/edd752916ad150c4ba6dc5cff411ed82a60493df/.github/workflows/ci.yml#L1159-L1160

**Comment by thxCode** [comment]
you might check if `cublas64_12.dll` exists under your CUDA installation path, e.g: `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.4\bin`.

**Comment by bugrootof** [comment]
![image](https://github.com/user-attachments/assets/2558e64e-9635-4e99-b45d-25c87366f841)
i have checked already,  but it doesn't have cublas64_12.dll file, only found cublas64_11.dll found. Do I need to update cuda？ @thxCode

**Comment by gitlawr** [comment]
The `nvidia-smi` prints CUDA version 12.6 while nvcc is using cuda 11.2. Is it ok to upgrade the toolkit to CUDA 12 in your enviornment? cuBLAS should be included as one of the Toolkit components.

**Comment by bugrootof** [comment]
![image](https://github.com/user-attachments/assets/707561dc-6d77-4e35-840c-ce784fac212d)
updated cuda 12.6 , but new problem arise  startup project page shows no GPU.
![image](https://github.com/user-attachments/assets/5a67dbe4-fcb0-4f2f-b03c-b0f962fca0b8)

**Comment by bugrootof** [comment]
sure,this is windos log
![image](https://github.com/user-attachments/assets/729434e6-1eb1-4549-8553-d7a0fe695fed)
@gitlawr

**Comment by gitlawr** [comment]
The worker will show up after initialization(including downloading tools) completes. It downloads from GitHub by default. If If your network connection to GitHub is slow, you can set the `--tools-download-base-url` flag. 

Rerun the installation script with the additional flag and it will apply.
```
Invoke-Expression "& { $((Invoke-WebRequest -Uri 'https://get.gpustack.ai' -UseBasicParsing).Content) } -- --tools-download-base-url 'https://gpustack-1303613262.cos.ap-guangzhou.myqcloud.com'"
```

Reference:
https://docs.gpustack.ai/latest/cli-reference/start/

**Comment by bugrootof** [comment]
After downloading according to your operation, the GPU is successfully displayed, but the model deployment is still the same problem as before cuda was not upgraded. Execute llama-box.exe -h without any output, and check the background log without error log. Give a screenshot of the result below.

1.GPU  is successfully displayed
![image](https://github.com/user-attachments/assets/51f5148a-0293-41ee-87ed-7c01d15ff9d7)
2.the same problem as before cuda was not upgraded
![image](https://github.com/user-attachments/assets/51f5148a-0293-41ee-87ed-7c01d15ff9d7)
3. run llama-box -h 
![image](https://github.com/user-attachments/assets/f57cb250-9ecc-4f53-b1e8-b6dd77925e66)
4. run "$env:APPDATA\gpustack\log\gpustack.log"
![image](https://github.com/user-attachments/assets/a236ced8-4bda-4c78-b408-4583b9b3f019)
@gitlawr

**Comment by gitlawr** [comment]
Have you tried installing `Visual C++ Redistributable for Visual Studio 2015-2022` as mentioned in https://github.com/gpustack/llama-box/issues/10#issuecomment-2544733124?

**Comment by bugrootof** [comment]
![image](https://github.com/user-attachments/assets/9d31b646-3320-4115-9404-72112198a954)
yes, i have install
@gitlawr

**Comment by bugrootof** [comment]
New logs:
2024-12-19T11:31:48+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 51024, pid 12608
2024-12-19T11:32:09+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 12608, restarting.
2024-12-19T11:32:09+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50167, pid 8624
2024-12-19T11:32:29+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 8624, restarting.
2024-12-19T11:32:29+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50870, pid 7628
2024-12-19T11:32:49+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 7628, restarting.
2024-12-19T11:32:49+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50020, pid 7932
2024-12-19T11:33:09+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 7932, restarting.
2024-12-19T11:33:09+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50353, pid 2260
2024-12-19T11:33:29+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 2260, restarting.
2024-12-19T11:33:29+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50143, pid 6956
2024-12-19T11:33:50+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 6956, restarting.
2024-12-19T11:33:50+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50371, pid 2460
2024-12-19T11:34:10+08:00 - gpustack.scheduler.calculator - INFO - Calculating resource claim for model instance bge-m3-Gr1OM
2024-12-19T11:34:10+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 2460, restarting.
2024-12-19T11:34:10+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50737, pid 13072
2024-12-19T11:34:10+08:00 - gpustack.scheduler.calculator - INFO - Calculated resource claim for full offload model instance bge-m3-Gr1OM, claim: memoryEstimate(fullOffloaded=True, ram=layerMemoryEstimate(uma=513983520, nonuma=671269920, handleLayers=0), vrams=[layerMemoryEstimate(uma=1128452680, nonuma=6088282696, handleLayers=24)], offloadLayers=25)
2024-12-19T11:34:10+08:00 - gpustack.scheduler.calculator - INFO - Calculating resource claim for model instance bge-m3-Gr1OM
2024-12-19T11:34:11+08:00 - gpustack.scheduler.calculator - INFO - Calculated resource claim for full offload model instance bge-m3-Gr1OM, claim: memoryEstimate(fullOffloaded=True, ram=layerMemoryEstimate(uma=513983520, nonuma=671269920, handleLayers=0), vrams=[layerMemoryEstimate(uma=1128452680, nonuma=6088282696, handleLayers=24)], offloadLayers=25)
2024-12-19T11:34:11+08:00 - gpustack.worker.serve_manager - INFO - Start serving model instance bge-m3-Gr1OM on port 40655
2024-12-19T11:34:30+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 13072, restarting.
2024-12-19T11:34:30+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50242, pid 13564
2024-12-19T11:34:50+08:00 - gpustack.worker.worker_manager - WARNING - RPC server for GPU 0 is not running, pid 13564, restarting.
2024-12-19T11:34:50+08:00 - gpustack.worker.worker_manager - INFO - Started RPC server for GPU 0 on port 50286, pid 12656

**Comment by pengjiang80** [comment]
After you run llama-box.exe -h without any output, could you check the event log to see if there are any application errors or warnings related to llama-box?

**Comment by bugrootof** [comment]
run you provide  ==eventvwr.msc== 
![image](https://github.com/user-attachments/assets/baf39d22-7c0f-4197-87f8-bc5c92444830)
@pengjiang80

**Comment by pengjiang80** [comment]
Thanks for your update. Based on the application crash event log and the VC++ redistribution package information you provided, the VC++ 2015-2022 redistribution package version you installed is a little bit old, 14.34.31931. There are some new versions, such as 14.40.33810. Could you download newer versions from below and try to update them?

https://aka.ms/vs/17/release/vc_redist.x86.exe
https://aka.ms/vs/17/release/vc_redist.x64.exe

Please restart your computer after the installation and have a try.

**Comment by bugrootof** [comment]
Now I have updated to the latest version  Microsoft Visual C++ 2015-2019 Redistributable  . run llama-box.exe -h it works.The model runs normally after downloading.But there were errors in model inference at the training ground(Service unavailable. Please retry your requests after a brief wait. Original error: All connection attempts failed)
1.Updated to the latest version. Run llama-box.exe -h 
![image](https://github.com/user-attachments/assets/71d37d37-b66f-4984-b437-13f57b9887c6)

2.Success runing
![image](https://github.com/user-attachments/assets/6e68d24e-4aef-47d8-ba7d-40b8c9370f2a)

3.New errors occur in model inference at the training ground
![image](https://github.com/user-attachments/assets/1fcc5c69-2a42-4999-b363-3990d2260ef8)

**Comment by gitlawr** [comment]
<img width="970" alt="image" src="https://github.com/user-attachments/assets/2d18311b-3940-4ccd-af1c-2dcd727d3c3b" />
What do you see in the instance logs?

**Comment by bugrootof** [comment]
Click View Logs button nothing, i found log file:

Downloading [qwen2.5-7b-instruct-q8_0-00002-of-00003.gguf]: 100%|█████████▉| 3.67G/3.67G [01:23<00:00, 22.3MB/s][A[A
Downloading [qwen2.5-7b-instruct-q8_0-00002-of-00003.gguf]: 100%|██████████| 3.67G/3.67G [01:23<00:00, 47.0MB/s]

Fetching 3 files:  67%|██████▋   | 2/3 [01:46<01:00, 60.28s/it]
Fetching 3 files: 100%|██████████| 3/3 [01:52<00:00, 35.63s/it]
Fetching 3 files: 100%|██████████| 3/3 [01:52<00:00, 37.56s/it]
2024-12-20T09:12:04+08:00 - gpustack.worker.backends.llama_box - INFO - Starting llama-box server
0.00.044.969 I ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
0.00.044.973 I ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
0.00.044.975 I ggml_cuda_init: found 1 CUDA devices:
0.00.044.985 I   Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
0.00.049.421 I 
0.00.049.425 I version: v0.0.93 (621ef0f)
0.00.049.425 I compiler: unknown
0.00.049.426 I target: unknown
0.00.049.426 I vendor: 
0.00.049.427 I   - llama.cpp d583cd03 (4318)
0.00.049.427 I   - stable-diffusion.cpp c8837bd (208)
0.00.049.494 I system_info: n_threads = 24 (n_threads_batch = 24) / 48 | CUDA : ARCHS = 600,610,700,750,800,860,890,900 | F16 = 1 | USE_GRAPHS = 1 | PEER_MAX_BATCH_SIZE = 128 | CPU : SSE3 = 1 | SSSE3 = 1 | AVX = 1 | AVX2 = 1 | F16C = 1 | FMA = 1 | LLAMAFILE = 1 | AARCH64_REPACK = 1 | 
0.00.049.494 I 
0.00.050.194 I srv                      main: listening, hostname = 0.0.0.0, port = 40332, n_threads = 6 + 2
0.00.054.884 I srv                      main: loading model
0.00.054.891 I srv                load_model: loading model ''
0.00.309.634 I llama_load_model_from_file: using device CUDA0 (NVIDIA GeForce RTX 3090) - 23305 MiB free
0.00.357.806 I llama_model_loader: additional 2 GGUFs metadata loaded.
0.00.357.811 I llama_model_loader: loaded meta data with 29 key-value pairs and 339 tensors from C:\Users\psdz\AppData\Roaming\gpustack\cache\model_scope\Qwen\Qwen2___5-7B-Instruct-GGUF\qwen2.5-7b-instruct-q8_0-00001-of-00003.gguf (version GGUF V3 (latest))
0.00.357.825 I llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
0.00.357.828 I llama_model_loader: - kv   0:                       general.architecture str              = qwen2
0.00.357.829 I llama_model_loader: - kv   1:                               general.type str              = model
0.00.357.831 I llama_model_loader: - kv   2:                               general.name str              = qwen2.5-7b-instruct
0.00.357.832 I llama_model_loader: - kv   3:                            general.version str              = v0.1
0.00.357.833 I llama_model_loader: - kv   4:                           general.finetune str              = qwen2.5-7b-instruct
0.00.357.834 I llama_model_loader: - kv   5:                         general.size_label str              = 7.6B
0.00.357.836 I llama_model_loader: - kv   6:                          qwen2.block_count u32              = 28
0.00.357.837 I llama_model_loader: - kv   7:                       qwen2.context_length u32              = 131072
0.00.357.838 I llama_model_loader: - kv   8:                     qwen2.embedding_length u32              = 3584
0.00.357.839 I llama_model_loader: - kv   9:                  qwen2.feed_forward_length u32              = 18944
0.00.357.840 I llama_model_loader: - kv  10:                 qwen2.attention.head_count u32              = 28
0.00.357.841 I llama_model_loader: - kv  11:              qwen2.attention.head_count_kv u32              = 4
0.00.357.855 I llama_model_loader: - kv  12:                       qwen2.rope.freq_base f32              = 1000000.000000
0.00.357.859 I llama_model_loader: - kv  13:     qwen2.attention.layer_norm_rms_epsilon f32              = 0.000001
0.00.357.860 I llama_model_loader: - kv  14:                          general.file_type u32              = 7
0.00.357.861 I llama_model_loader: - kv  15:                       tokenizer.ggml.model str              = gpt2
0.00.357.862 I llama_model_loader: - kv  16:                         tokenizer.ggml.pre str              = qwen2
0.00.403.978 I llama_model_loader: - kv  17:                      tokenizer.ggml.tokens arr[str,152064]  = ["!", "\"", "#", "$", "%", "&", "'", ...
0.00.421.530 I llama_model_loader: - kv  18:                  tokenizer.ggml.token_type arr[i32,152064]  = [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...
0.00.467.692 I llama_model_loader: - kv  19:                      tokenizer.ggml.merges arr[str,151387]  = ["Ġ Ġ", "ĠĠ ĠĠ", "i n", "Ġ t",...
0.00.467.695 I llama_model_loader: - kv  20:                tokenizer.ggml.eos_token_id u32              = 151645
0.00.467.696 I llama_model_loader: - kv  21:            tokenizer.ggml.padding_token_id u32              = 151643
0.00.467.697 I llama_model_loader: - kv  22:                tokenizer.ggml.bos_token_id u32              = 151643
0.00.467.698 I llama_model_loader: - kv  23:               tokenizer.ggml.add_bos_token bool             = false
0.00.467.703 I llama_model_loader: - kv  24:                    tokenizer.chat_template str              = {%- if tools %}\n    {{- '<|im_start|>...
0.00.467.704 I llama_model_loader: - kv  25:               general.quantization_version u32              = 2
0.00.467.705 I llama_model_loader: - kv  26:                                   split.no u16              = 0
0.00.467.705 I llama_model_loader: - kv  27:                                split.count u16              = 3
0.00.467.706 I llama_model_loader: - kv  28:                        split.tensors.count i32              = 339
0.00.467.707 I llama_model_loader: - type  f32:  141 tensors
0.00.467.708 I llama_model_loader: - type q8_0:  198 tensors
0.00.640.971 I llm_load_vocab: special tokens cache size = 22
0.00.681.425 I llm_load_vocab: token to piece cache size = 0.9310 MB
0.00.681.435 I llm_load_print_meta: format           = GGUF V3 (latest)
0.00.681.436 I llm_load_print_meta: arch             = qwen2
0.00.681.437 I llm_load_print_meta: vocab type       = BPE
0.00.681.438 I llm_load_print_meta: n_vocab          = 152064
0.00.681.438 I llm_load_print_meta: n_merges         = 151387
0.00.681.439 I llm_load_print_meta: vocab_only       = 0
0.00.681.439 I llm_load_print_meta: n_ctx_train      = 131072
0.00.681.440 I llm_load_print_meta: n_embd           = 3584
0.00.681.440 I llm_load_print_meta: n_layer          = 28
0.00.681.454 I llm_load_print_meta: n_head           = 28
0.00.681.457 I llm_load_print_meta: n_head_kv        = 4
0.00.681.457 I llm_load_print_meta: n_rot            = 128
0.00.681.458 I llm_load_print_meta: n_swa            = 0
0.00.681.458 I llm_load_print_meta: n_embd_head_k    = 128
0.00.681.459 I llm_load_print_meta: n_embd_head_v    = 128
0.00.681.461 I llm_load_print_meta: n_gqa            = 7
0.00.681.464 I llm_load_print_meta: n_embd_k_gqa     = 512
0.00.681.466 I llm_load_print_meta: n_embd_v_gqa     = 512
0.00.681.472 I llm_load_print_meta: f_norm_eps       = 0.0e+00
0.00.681.473 I llm_load_print_meta: f_norm_rms_eps   = 1.0e-06
0.00.681.474 I llm_load_print_meta: f_clamp_kqv      = 0.0e+00
0.00.681.475 I llm_load_print_meta: f_max_alibi_bias = 0.0e+00
0.00.681.475 I llm_load_print_meta: f_logit_scale    = 0.0e+00
0.00.681.478 I llm_load_print_meta: n_ff             = 18944
0.00.681.479 I llm_load_print_meta: n_expert         = 0
0.00.681.479 I llm_load_print_meta: n_expert_used    = 0
0.00.681.479 I llm_load_print_meta: causal attn      = 1
0.00.681.480 I llm_load_print_meta: pooling type     = 0
0.00.681.480 I llm_load_print_meta: rope type        = 2
0.00.681.481 I llm_load_print_meta: rope scaling     = linear
0.00.681.482 I llm_load_print_meta: freq_base_train  = 1000000.0
0.00.681.483 I llm_load_print_meta: freq_scale_train = 1
0.00.681.484 I llm_load_print_meta: n_ctx_orig_yarn  = 131072
0.00.681.485 I llm_load_print_meta: rope_finetuned   = unknown
0.00.681.485 I llm_load_print_meta: ssm_d_conv       = 0
0.00.681.485 I llm_load_print_meta: ssm_d_inner      = 0
0.00.681.488 I llm_load_print_meta: ssm_d_state      = 0
0.00.681.488 I llm_load_print_meta: ssm_dt_rank      = 0
0.00.681.489 I llm_load_print_meta: ssm_dt_b_c_rms   = 0
0.00.681.490 I llm_load_print_meta: model type       = 7B
0.00.681.490 I llm_load_print_meta: model ftype      = Q8_0
0.00.681.492 I llm_load_print_meta: model params     = 7.62 B
0.00.681.493 I llm_load_print_meta: model size       = 7.54 GiB (8.50 BPW) 
0.00.681.494 I llm_load_print_meta: general.name     = qwen2.5-7b-instruct
0.00.681.494 I llm_load_print_meta: BOS token        = 151643 '<|endoftext|>'
0.00.681.495 I llm_load_print_meta: EOS token        = 151645 '<|im_end|>'
0.00.681.495 I llm_load_print_meta: EOT token        = 151645 '<|im_end|>'
0.00.681.496 I llm_load_print_meta: PAD token        = 151643 '<|endoftext|>'
0.00.681.497 I llm_load_print_meta: LF token         = 148848 'ÄĬ'
0.00.681.497 I llm_load_print_meta: FIM PRE token    = 151659 '<|fim_prefix|>'
0.00.681.498 I llm_load_print_meta: FIM SUF token    = 151661 '<|fim_suffix|>'
0.00.681.499 I llm_load_print_meta: FIM MID token    = 151660 '<|fim_middle|>'
0.00.681.499 I llm_load_print_meta: FIM PAD token    = 151662 '<|fim_pad|>'
0.00.681.500 I llm_load_print_meta: FIM REP token    = 151663 '<|repo_name|>'
0.00.681.500 I llm_load_print_meta: FIM SEP token    = 151664 '<|file_sep|>'
0.00.681.501 I llm_load_print_meta: EOG token        = 151643 '<|endoftext|>'
0.00.681.501 I llm_load_print_meta: EOG token        = 151645 '<|im_end|>'
0.00.681.502 I llm_load_print_meta: EOG token        = 151662 '<|fim_pad|>'
0.00.681.502 I llm_load_print_meta: EOG token        = 151663 '<|repo_name|>'
0.00.681.503 I llm_load_print_meta: EOG token        = 151664 '<|file_sep|>'
0.00.681.503 I llm_load_print_meta: max token length = 256
0.00.831.981 I llm_load_tensors: offloading 28 repeating layers to GPU
0.00.831.984 I llm_load_tensors: offloading output layer to GPU
0.00.831.985 I llm_load_tensors: offloaded 29/29 layers to GPU
0.00.832.003 I llm_load_tensors:    CUDA_Host model buffer size =   552.23 MiB
0.00.832.005 I llm_load_tensors:        CUDA0 model buffer size =  7165.44 MiB
........................................................................................
0.03.448.743 I llama_new_context_with_model: n_seq_max     = 4
0.03.448.745 I llama_new_context_with_model: n_ctx         = 8192
0.03.448.746 I llama_new_context_with_model: n_ctx_per_seq = 2048
0.03.448.746 I llama_new_context_with_model: n_batch       = 2048
0.03.448.747 I llama_new_context_with_model: n_ubatch      = 512
0.03.448.747 I llama_new_context_with_model: flash_attn    = 0
0.03.448.754 I llama_new_context_with_model: freq_base     = 1000000.0
0.03.448.755 I llama_new_context_with_model: freq_scale    = 1
0.03.448.758 W llama_new_context_with_model: n_ctx_per_seq (2048) < n_ctx_train (131072) -- the full capacity of the model will not be utilized
0.03.466.000 I llama_kv_cache_init:      CUDA0 KV buffer size =   448.00 MiB
0.03.466.005 I llama_new_context_with_model: KV self size  =  448.00 MiB, K (f16):  224.00 MiB, V (f16):  224.00 MiB
0.03.466.763 I llama_new_context_with_model:  CUDA_Host  output buffer size =     0.05 MiB
0.03.480.585 I llama_new_context_with_model:      CUDA0 compute buffer size =   492.00 MiB
0.03.480.589 I llama_new_context_with_model:  CUDA_Host compute buffer size =    23.01 MiB
0.03.480.590 I llama_new_context_with_model: graph nodes  = 986
0.03.480.590 I llama_new_context_with_model: graph splits = 2
0.03.482.403 I srv                      main: initializing server
0.03.482.412 I srv                      init: initializing slots, n_slots = 4
0.03.483.543 I srv                      main: chat template, built_in: 1, chat_example:
<|im_start|>system
You are a helpful assistant<|im_end|>
<|im_start|>user
Hello<|im_end|>
<|im_start|>assistant
Hi there<|im_end|>
<|im_start|>user
How are you?<|im_end|>
<|im_start|>assistant

0.03.483.553 I srv                      main: starting server

**Comment by gitlawr** [comment]
Now it runs as expected. How many nodes do you have? If you have multiple nodes, connectivity between nodes are required: https://docs.gpustack.ai/latest/installation/installation-requirements/#connectivity-requirements

**Comment by gitlawr** [comment]
> Service unavailable. Please retry your requests after a brief wait. Original error: All connection attempts failed

It could happen when the model instance is initializing, does it work after some time?

**Comment by bugrootof** [comment]
I tried again three hours later with the same mistake：Service unavailable. Please retry your requests after a brief wait. Original error: All connection attempts failed
![image](https://github.com/user-attachments/assets/4b5bdd50-9274-4bca-80f7-e6a496b14cbc)

**Comment by gitlawr** [comment]
It don't need to be that long. Given the above logs the inference backend is ready to serve.

<img width="328" alt="image" src="https://github.com/user-attachments/assets/1139079f-edd3-4497-a3a2-ef63b526a9bb" />

You can check direct access the the instance, for example: 
```
$ curl 192.168.50.70:40676/health
{"status":"ok"}
```

If it's not accessible, it could be windows firewall issues

**Comment by bugrootof** [comment]
Thanks, really like you said, so how should I set up the firewall?
![image](https://github.com/user-attachments/assets/aa09ed15-e7b4-40bf-8eec-0e14c661b1f4)

**Comment by gitlawr** [comment]
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/594c538e-4bfc-4e29-abc7-ebd538f26fac" />
Go to settings -> firewall -> advanced -> Inbound Rules. To make it simple, you can create a new rule that allows all programs or ports to check if this is the cause.

**Comment by pengjiang80** [comment]
Could you check the resource - worker page and confirm the worker ip address registered? If you only have one worker (the same as the server), the connection should be within your PC. The default Windows firewall setting should not block this connection.

**Comment by bugrootof** [comment]
@pengjiang80 我只有一个worker(与服务器ip相同),我也纳闷了，默认的 Windows 防火墙设置不应阻止此连接才对。
![image](https://github.com/user-attachments/assets/a0c88d6e-70de-445a-8e56-de2a9c77a266)

**Comment by pengjiang80** [comment]
We will do some tests and get back to you. Meanwhile, you can explicitly add an inbound rule to allow connection to the inference service port to see if it helps.

**Comment by bugrootof** [comment]
ok, i will do add in inbound rule to allow connection to the inference

**Comment by pengjiang80** [comment]
Does it work after creating the firewall rule? I just did some tests on a Win11 laptop. The default Windows firewall settings don't block the connection inside the computer. There may be some non-default rules blocking the connection.

**Comment by bugrootof** [comment]
After creating the firewall rule, the request was block. I have a question, I only have a single node locally, and it is deployed locally, but the IP segment assigned is not my local IP segment

1. add the firedwall rule open all ports simultaneously
![image](https://github.com/user-attachments/assets/d681ebae-99d8-463b-8747-79cf3bdf9f29)
2.the request was blocked
![image](https://github.com/user-attachments/assets/4ed03bc8-c256-4e91-bc2c-611ddb53897e)

**Comment by gitlawr** [comment]
If the IP is incorrect, then it's irrelevant to firewall settings. 
You can rerun the installation script with `--worker-ip`, for example:
```
Invoke-Expression "& { $((Invoke-WebRequest -Uri 'https://get.gpustack.ai' -UseBasicParsing).Content) } -- --worker-ip '192.168.110.10'"
```
Then delete the model instance so that GPUStack will recreate it with the updated IP.

Is the `10.*.*.*` IP present in any of your network interfaces?

**Comment by bugrootof** [comment]
Thank you, it has been successful! I installed on another windos computer, the windows firewall will not block the connection by default, and the model was successfully deployed. When the IP segments are inconsistent, execute: Invoke - Expression "& { $(( Invoke - Web Request -Uri 'https://get.gpustack.ai' -UseBasicParsing).Content ) } -- -- worker - ip '192.168.110.10' "After specifying the ip of the same network segment as the local machine, since I have an RTX3090 graphics card, the number of GPUs after entering the page is 0, and then I uninstall and execute: Invoke - Expression "& { $(( Invoke - Web Request -Uri https://get.gpustack.ai '-UseBasicParsing).
Content) } --worker-ip '192.168.110.10' --port 9999 --tools-download-base-url 'https://gpustack-1303613262.cos.ap-guangzhou.myqcloud.com' "Enter the page GPU shows that the number of available is 1, and the model deployment and inference are all normal.

**Comment by bugrootof** [comment]
Thank you, it has been successful! I installed on another windos computer, the windows firewall will not block the connection by default, and the model was successfully deployed. When the IP segments are inconsistent, execute: Invoke - Expression "& { $(( Invoke - Web Request -Uri 'https://get.gpustack.ai' -UseBasicParsing). Content ) } -- -- worker - ip '192.168.110.10' "After specifying the ip of the same network segment as the local machine, since I have an RTX3090 graphics card, the number of GPUs after entering the page is 0, and then I uninstall and execute: Invoke - Expression "& { $(( Invoke - Web Request -Uri https://get.gpustack.ai '-UseBasicParsing).
Content) } --worker-ip '192.168.110.10' --port 9999 --tools-download-base-url 'https://gpustack-1303613262.cos.ap-guangzhou.myqcloud.com' "Enter the page GPU shows that the number of available is 1, and the model deployment and inference are all normal.
