### ISSUE TITLE
--ctx-size is not usefull on embedding for llama-box engine

### ISSUE THREAD

**Issue by verigle** [gpustack/gpustack#811]
**Describe the bug**

**Steps to reproduce**

1. deploy model from Ollama Library/viosay/conan-embedding-v1, backend using llama-box with param --ctx-size=8192

**Result**

--ctx-size only has default 512

**context size change to 8192**

**Environment**

- GPUStack version: v0.4.1
- OS: ubuntu
- GPU: t4

**Additional context**

**Comment by gitlawr** [comment]
512 is the maximum of this model:https://huggingface.co/TencentBAC/Conan-embedding-v1/blob/main/config.json#L16

**Comment by verigle** [comment]
is there any way to supports context size up to 128K tokens of qwen2.5  instead default context size 32768 like ollama ?https://ollama.com/library/qwen2.5
<img width="892" alt="image" src="https://github.com/user-attachments/assets/36d4bb0a-b78b-43e0-9379-165d2fefb58b" />

https://huggingface.co/Qwen/Qwen2.5-72B-Instruct/blob/main/config.json
<img width="805" alt="image" src="https://github.com/user-attachments/assets/37a48fcc-4b15-47df-af1e-e7a5a4a54ffb" />

**Comment by gitlawr** [comment]
128K is for the non-instrruct model(https://huggingface.co/Qwen/Qwen2.5-72B/blob/main/config.json#L12)

It's not something ollama extend.
