### ISSUE TITLE
feature: Dockerfile / docker-compose

### ISSUE THREAD

**Issue by sammcj** [gpustack/gpustack#92]
**Describe the solution you'd like**

GPUStack looks like a really interesting idea, it would benefit from having a Dockerfile and an example docker-compose so folks could easily deploy it to their machines.

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by gitlawr** [comment]
We haven't provide the docker installation way because it does not work in some cases. For example, Apple silicon does not support GPU passthrough.
I agree it would be convinent to provide the Dockerfile or official docker image and clarify the use cases.

**Comment by sammcj** [comment]
Ah yes, although - lots of enthusiasts have have home server or gaming machine at home (or across several cloud providers) with an nvidia GPU they'd love to put to use for exactly this.

I think the project is really neat - I can't wait to see where you go with it!

**Comment by sammcj** [comment]
Actually - if you installation steps that don't do a curl | bash or assume systemd is present I might be able to submit a PR with a working Dockerfile and example docker-compose.yml for CUDA machines?

**Comment by gitlawr** [comment]
It should be straightforward as
```
FROM python:3.10
RUN pip install gpustack

ENTRYPOINT ["gpustack"]
CMD ["start"]
```

There are issues we need to resolve before providing this to users(e.g., there are errors when GPUs are not available). But you can get started from here.

**Comment by Finenyaco** [comment]
Verified in [ddd7451](https://github.com/gpustack/gpustack/commit/ddd74515aaadecf979553e90ab74853a16e01484). Please note that currently only Ubuntu + NVIDIA GPUs are supported.
