### ISSUE TITLE
Dashboard response 500 when there's no worker

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#93]
**Describe the bug**

<img width="1418" alt="image" src="https://github.com/user-attachments/assets/b142a801-20ae-4838-bf84-11cf61744f76">

**Steps to reproduce**

1. Run `curl -sfL https://get.gpustack.ai | sh -s - --disable-worker` to install
2. Access the dashboard UI.

**Expected behavior**

No errors.

**Comment by Sunwood-ai-labs** [comment]
I'm encountering the same error.

**Comment by Finenyaco** [comment]
**Environment**
- GPUStack version: main(f530289)
- UI version: cfdc731
- OS:  MacOS 14.2.1
- GPU: Apple M2, 24G

**Test Result:** pass

<img width="2478" alt="image" src="https://github.com/user-attachments/assets/2f6d8c1b-1d29-480f-a17a-5828bc3d4e96">

**Comment by Sunwood-ai-labs** [comment]
thank you! It worked fine
