### ISSUE TITLE
Support Embeddings and Completions API

### ISSUE THREAD

**Issue by gitlawr** [gpustack/gpustack#95]
**Is your enhancement related to a problem? Please describe.**

Support [OpenAI compatible](https://platform.openai.com/docs/api-reference) embeddings and completions APIs.

**Comment by aiwantaozi** [comment]
Known problems for bge-m3 are recorded in https://github.com/gpustack/gpustack/issues/147

**Comment by Finenyaco** [comment]
Verified in 5f2ecc0
