### ISSUE TITLE
[ERROR] Failed to install GPUStack: "Failed to install GPUStack: "pipx >(setup:1083): pipx version is 1.6.0""

### ISSUE THREAD

**Issue by yknothing** [gpustack/gpustack#96]
My environment is  Windows 11 & RTX 4060. I correctly installed CUDA and Python 3.12.4 (with pipx 1.6.0), but I got an error when installing GPUStack. I checked that the pipx Environment Variable is correct, and I tried to reinstall the pipx and restart the PC, but there's no change.

**Comment by aiwantaozi** [comment]
Could you please let us know which PowerShell tool and version you are using to run the script? We encountered a similar issue on Windows ISE where the logs from pipx were interpreted as error messages, triggering the exception handling mechanism.

Here is the install log from Window Powershell, you see the pipx version is 1.6.0.
<img width="754" alt="image" src="https://github.com/user-attachments/assets/f7f7782c-3cd5-49c4-9983-33484618591b">


Could you try running the installation script in Windows PowerShell (Console) to see if it installs correctly? We will consider supporting Windows ISE in the future.

Thank you.

**Comment by gitlawr** [comment]
We clarified in the documentation to avoid using PowerShell ISE for the installation. If that’s not your case, feel free to reopen the issue or give us feedback.

**Comment by yknothing** [comment]
Sorry, just saw your messages. I indeed ran it in Windows PowerShell ISE previously. I tried again  in Windows PowerShell and it was successful. Thanks for your reply!
