### ISSUE TITLE
Support binpack and spread when schedule model instance base on the resource.

### ISSUE THREAD

**Issue by aiwantaozi** [gpustack/gpustack#99]
Binpack: This strategy aims to consolidate model instances into the fewest workers. It attempts to pack model instances into a minimal number of workers, maximizing resource utilization on those workers. 

Spread: In contrast, the spread strategy aims to distribute model instances evenly across all available workers. It spreads model instances out to balance the load, ensuring no single resource is overwhelmed.

**Comment by Finenyaco** [comment]
Verified in main 4d42dce
